'use client'
import React, { createContext, useContext, useState, ReactNode } from "react";

type Language = "en" | "ar";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, unknown>) => string;
  isRTL: boolean;
}

const translations = {
  en: {
    // Table
    "table.toggleDetails": "Toggle details",
    // Common
    "common.noResults": "No results",

    // Header
    "header.title": "University of Ha'il",
    "header.subtitle": "Biomedical Equipment Dashboard",
    "header.department": "Maintenance Department",
    "header.facility": "Facility Management",
    
    // Equipment Card
    "equipment.name": "Equipment/Device Name",
    "equipment.label": "Equipment/Device",
    "equipment.upToDate": "Up to Date",
    "equipment.dueSoon": "Due Soon", 
    "equipment.overdue": "Overdue",
    "equipment.lastMaintenance": "Last Maintenance",
    "equipment.nextMaintenance": "Next Maintenance",
    "equipment.location": "Location",
    "equipment.inDays": "In {days} days",
    "equipment.overdueBy": "Overdue by {days} days",
    "equipment.every": "Every",
    "equipment.sparePartsRequired": "Spare Parts Required",
    "equipment.approved": "Approved",
    "equipment.pendingApproval": "Pending Approval",
    "equipment.requestApproval": "Request Approval",
    "equipment.scheduleMaintenance": "Schedule Maintenance",
    "equipment.part": "Tag Number",
    "equipment.edit": "Edit",
    "equipment.inUse": "In Use",
    "equipment.notInUse": "Not In Use",
    "equipment.status": "Status",
    "equipment.markMaintenanceCompleted": "Mark Maintenance Completed",
    "equipment.equipmentUpdated": "Equipment Updated",
    "equipment.delete": "Delete",
    "equipment.deleteTitle": "Delete equipment?",
    "equipment.deleteDescription": "This will remove {name} from the list.",
    "equipment.noMaintenanceSchedule": "No maintenance scheduled",
    
    // Add Equipment Form
    "form.addNewEquipment": "Add New Equipment",
    "form.machineName": "Equipment/Device name",
    "form.partNumber": "Tag Number",
    "form.location": "Location",
    "form.maintenanceInterval": "Maintenance Interval",
    "form.lastMaintenanceDate": "Last Maintenance Date",
    "form.sparePartsRequired": "Spare parts required for maintenance",
    "form.selectInterval": "Select interval",
    "form.everyWeek": "Every Week",
    "form.every2Weeks": "Every 2 Weeks", 
    "form.everyMonth": "Every Month",
    "form.every3Months": "Every 3 Months",
    "form.every6Months": "Every 6 Months",
    "form.everyYear": "Every Year",
    "form.addEquipment": "Add Equipment",
    "form.cancel": "Cancel",
    "form.required": "*",
    "form.edit": "Edit",
    "form.save": "Save",
    "form.back": "Back",
    "form.next": "Next",
    "form.model": "Model",
    "form.manufacturer": "Manufacturer",
    "form.serialNumber": "Serial Number",
    "form.status": "Status",
    "form.selectStatus": "Select status",
    "form.subLocation": "Sub-location",
    "form.newInstallation": "New Installation",
    "form.working": "Working",
    "form.repair": "Repair",
    "form.maintenance": "Maintenance",
    "form.partReplacement": "Part Replacement",
    "form.forInstallation": "For Installation",
    
    // Alerts
    "alert.allCurrent": "All Equipment Current",
    "alert.allCurrentDesc": "All equipment maintenance schedules are up to date.",
    "alert.overdueMaintenance": "Overdue Maintenance",
    "alert.overdueCount": "{count} equipment item overdue for maintenance.|{count} equipment items overdue for maintenance.",
    "alert.dueSoon": "Maintenance Due Soon",
    "alert.dueSoonCount": "{count} equipment item due for maintenance within 7 days.|{count} equipment items due for maintenance within 7 days.",
    "alert.scheduleOverview": "Maintenance Schedule Overview",
    
    // Search and Filter
    "search.placeholder": "Search equipment...",
    "filter.byStatus": "Filter by status",
    "filter.allEquipment": "All Equipment",
    "filter.upToDate": "Up to Date",
    "filter.dueSoon": "Due Soon",
    "filter.overdue": "Overdue",
    "filter.all": "All",
    "search.noResults": "No equipment found matching your criteria.",
    // CSV
    "csv.export": "Export CSV",
    "csv.import": "Import CSV",
    "csv.importing": "Importing...",
    "csv.imported": "CSV imported successfully",
    "csv.noRows": "No data rows found in CSV",
    "csv.missingHeaders": "Missing required headers: {missing}",
    "csv.downloadTemplate": "Download Template",
    "csv.templateDownloaded": "Template downloaded successfully",
    // List label
    "list.label.showing": "Showing {from}-{to} of {total}",
    "list.label.filteredBy": "filtered by",
    "list.label.search": "search \"{q}\"",
    "list.label.status": "status: {status}",
    "list.label.and": "and",
    
    // Toast Messages
    "toast.error": "Error",
    "toast.fillRequired": "Please fill in all required fields",
    "toast.success": "Success", 
    "toast.equipmentAdded": "Equipment added successfully",
    "toast.equipmentUpdated": "Equipment updated successfully",
    "toast.maintenanceScheduled": "Maintenance Scheduled",
    "toast.maintenanceScheduledDesc": "Maintenance for {name} has been scheduled.",
    "toast.serviceRequestCreated": "Service request created",
    "toast.serviceRequestUpdated": "Service request updated",
    "toast.updated": "Updated successfully",
    
    // Language
    "language.switch": "العربية",
    "language.current": "English",
    
    // Auth
    "auth.signOut": "Sign out",
    "auth.brand.title": "University of Ha'il",
    "auth.brand.subtitle": "Equipment Maintenance System",
    "auth.signup.title": "Create your account",
    "auth.signup.name": "Full name",
    "auth.signup.name.placeholder": "e.g. Jane Doe",
    "auth.signup.email": "Email",
    "auth.signup.email.placeholder": "you@example.com",
    "auth.signup.password": "Password",
    "auth.signup.password.placeholder": "••••••••",
    "auth.signup.password.helper": "At least 8 characters with a letter and number.",
    "auth.signup.confirm": "Confirm password",
    "auth.signup.confirm.placeholder": "••••••••",
    "auth.signup.submit": "Create account",
    "auth.signup.haveAccount": "Already have an account?",
    "auth.signup.signIn": "Sign in",
    "auth.error.nameEmailRequired": "Please enter name and email",
    "auth.error.passwordConfirmRequired": "Please enter and confirm your password",
    "auth.error.passwordsNoMatch": "Passwords do not match",
    "auth.error.passwordWeak": "Password must be 8+ chars, include a letter and number",
    "auth.success.accountCreated": "Account created. Please sign in.",
    "auth.pendingApprovalTitle": "Account Pending Approval",
    "auth.pendingApprovalDesc": "Your account has been created and is awaiting approval. Please contact your supervisor or administrator to activate access.",
    "priority.low": "Low",
    "priority.medium": "Medium",
    "priority.high": "High",
    "priority.urgent": "Urgent",
    
    // Service Request Status Labels
    "serviceRequest.needsApproval": "Needs Approval",
    "serviceRequest.awaitingApproval": "Awaiting Approval",
    "serviceRequest.overdue": "Overdue",

    // Service Request
    "serviceRequest.title": "Service Request",
    "serviceRequest.manage": "Manage",
    "serviceRequest.manageRequests": "Manage Service Requests",
    "serviceRequest.newRequest": "Raise Service Request",
    "serviceRequest.createTitle": "Create Service Request",
    "serviceRequest.editTitle": "Edit Service Request",
    "serviceRequest.description": "Fill in the details below to raise a service request.",
    "serviceRequest.basic": "Basic",
    "serviceRequest.details": "Technician Details",
    "serviceRequest.requestType": "Request Type",
    "serviceRequest.selectType": "Select type",
    "serviceRequest.types.preventive": "Preventive maintenance",
    "serviceRequest.types.corrective": "Corrective maintenance",
    "serviceRequest.types.install": "Install",
    "serviceRequest.types.assess": "Assess",
    "serviceRequest.types.other": "Other",
    "serviceRequest.priority": "Priority",
    "serviceRequest.selectPriority": "Select priority",
    "serviceRequest.priorities.low": "Low",
    "serviceRequest.priorities.medium": "Medium",
    "serviceRequest.priorities.high": "High",
    "serviceRequest.scheduledAt": "Scheduled At",
    "serviceRequest.problemDescription": "Problem Description",
    "serviceRequest.problemPlaceholder": "Describe the problem...",
    "serviceRequest.technicalAssessment": "Technical Assessment",
    "serviceRequest.assessmentPlaceholder": "Enter technical assessment...",
    "serviceRequest.recommendation": "Recommendation",
    "serviceRequest.recommendationPlaceholder": "Enter recommendation...",
    "serviceRequest.viewEquipment": "View equipment",
    "serviceRequest.status": "Status",
    "serviceRequest.approvalStatus": "Approval Status",
    "serviceRequest.workStatus": "Operational Status",
    "serviceRequest.operational.status": "Operational Status",
    "serviceRequest.operational.operational": "Operational",
    "serviceRequest.operational.underRepair": "Under Repair, Waiting for Spare Parts",
    "serviceRequest.operational.select": "Select Operational Status",
    "serviceRequest.statuses.pending": "Pending",
    "serviceRequest.statuses.approved": "Approved",
    "serviceRequest.statuses.rejected": "Rejected",
    "serviceRequest.statuses.completed": "Completed",
    "serviceRequest.statuses.cancelled": "Cancelled",
    "serviceRequest.create": "Create Request",
    "serviceRequest.addDetails": "Add Details",
    "serviceRequest.detailsPendingTitle": "Technician details pending",
    "serviceRequest.detailsPendingDesc": "Complete assessment, recommendation, and spare parts.",
    "serviceRequest.openRequest": "Open request",
    "serviceRequest.view": "View",
    "serviceRequest.selectTechnician": "Select Technician",
    "serviceRequest.assignedTechnician": "Technician",
    "serviceRequest.assignedToMe": "Assigned to me",
    "serviceRequest.none": "None",

    // Spare parts in Service Request
    "serviceRequest.spareParts.title": "Spare Parts",
    "serviceRequest.spareParts.part": "Part name",
    "serviceRequest.spareParts.description": "Description (optional)",
    "serviceRequest.spareParts.quantity": "Qty",
    "serviceRequest.spareParts.cost": "Cost",
    "serviceRequest.spareParts.source": "Source/Supplier",
    "serviceRequest.spareParts.add": "Add",
    "serviceRequest.spareParts.remove": "Remove",
    "serviceRequest.spareParts.empty": "No spare parts needed.",
    "serviceRequest.spareParts.total": "Total: {amount}",
    "serviceRequest.spareParts.validation": "Please enter part name and quantity",
    "serviceRequest.ticketId": "Ticket ID",
    "serviceRequest.stats.total": "Total",
    "serviceRequest.stats.preventive": "Preventive",
    "serviceRequest.stats.corrective": "Corrective",
    "serviceRequest.stats.install": "Install",
    "serviceRequest.stats.assess": "Assess",
    "serviceRequest.stats.other": "Other",
    "serviceRequest.stats.assignedToMe": "Assigned to Me",

    // Users
    "users.title": "Users",
    "users.role": "Role",
    "users.email": "Email",
    "users.displayName": "Display Name",
    "users.create": "Create",
    "users.passwordSetupNote": "After creating a user without a password, share the password setup link:",
    "users.copyLink": "Copy link",
    "users.copied": "Link copied",
    "users.copyError": "Failed to copy link",

    // Settings
    "settings.title": "Settings",
    "settings.subtitle": "Manage your account, preferences and appearance.",
    "settings.account": "Account",
    "settings.email": "Email",
    "settings.displayName": "Display name",
    "settings.phone": "Phone",
    "settings.phonePlaceholder": "e.g. +966 5XXXXXXXX",
    "settings.designation": "Designation",
    "settings.designationPlaceholder": "e.g. Biomedical Engineer",
    "settings.department": "Department",
    "settings.departmentPlaceholder": "e.g. Maintenance",
    "settings.resetPassword": "Reset password",
    "settings.saving": "Saving...",
    "settings.save": "Save changes",
    "settings.appearance": "Appearance",
    "settings.theme": "Theme",
    "settings.themeQuick": "Quick theme",
    "settings.themeHint": "Choose light, dark or system",
    "settings.language": "Language",
    "settings.selectLanguage": "Select language",
    
    // Sidebar
    "sidebar.menu": "Menu",
    "sidebar.home": "Home",
    "sidebar.inventory": "Inventory",
    "sidebar.locations": "Locations",
    "sidebar.jobOrders": "Job Orders",
    "sidebar.serviceRequests": "Service Requests",
    "sidebar.preventiveMaintenance": "Preventive Maintenance",
    "sidebar.reports": "Reports",
    "sidebar.manageUsers": "Manage Users",
    "sidebar.accountSettings": "Account / Settings",

    // Locations
    "locations.title": "Locations",
    "locations.subtitle": "Manage locations across all campuses",
    "locations.addLocation": "Add New Location",
    "locations.campus": "Campus",
    "locations.locationName": "Location Name",
    "locations.selectCampus": "Select campus",
    "locations.enterName": "e.g., Engineering Building",
    "locations.addButton": "Add Location",
    "locations.allLocations": "All Locations",
    "locations.showAll": "Show All Locations",
    "locations.noLocations": "No locations added yet",
    "locations.noLocationsFiltered": "No locations found for {campus}",
    "locations.addFirst": "Add your first location above",
    "locations.delete": "Delete Location",
    "locations.deleteConfirm": "Are you sure you want to delete \"{name}\"? This action cannot be undone.",
    "locations.deleteSuccess": "Location deleted successfully",
    "locations.viewEquipment": "View equipment for this location",
    "locations.equipmentItems": "Equipment Items",
    "locations.workingEquipment": "Working Equipment",
    "locations.noEquipment": "No equipment in this location yet",
    "locations.equipmentWillAppear": "Equipment will appear here once added",
    "locations.general": "General",

    // Job Orders
    "jobOrders.title": "Job Orders",
    "jobOrders.subtitle": "Manage job orders and work requests",

    // Dashboard
    "dashboard.locations": "Locations",
    "dashboard.locationsDesc": "Manage campus locations and view equipment distribution",
    "dashboard.jobOrders": "Job Orders",
    "dashboard.jobOrdersDesc": "Create job orders for equipment maintenance and service requests",

    // Spare Parts
    "spareParts.title": "Spare Parts",
    "spareParts.addSparePart": "Add Spare Part",
    "spareParts.name": "Name",
    "spareParts.serialNumber": "Serial Number",
    "spareParts.quantity": "Quantity",
    "spareParts.manufacturer": "Manufacturer",
    "spareParts.supplier": "Supplier",
    "spareParts.noResults": "No spare parts found.",
    "spareParts.deleteTitle": "Delete Spare Part",
    "spareParts.deleteDescription": "Are you sure you want to delete \"{name}\"? This action cannot be undone.",
    "spareParts.addSuccess": "Spare part added successfully!",
    "spareParts.updateSuccess": "Spare part updated successfully!",
    "spareParts.deleteSuccess": "Spare part deleted successfully!",
    "spareParts.addError": "Failed to add spare part",
    "spareParts.updateError": "Failed to update spare part",
    "spareParts.deleteError": "Failed to delete spare part",
    "spareParts.nameRequired": "Name is required",
    "spareParts.adding": "Adding...",
    "spareParts.deleteConfirm": "Are you sure you want to delete this spare part?",
    "spareParts.namePlaceholder": "e.g., Air Filter",
    "spareParts.serialNumberPlaceholder": "e.g., SN-12345",
    "spareParts.quantityPlaceholder": "e.g., 10",
    "spareParts.manufacturerPlaceholder": "e.g., Acme Corp",
    "spareParts.supplierPlaceholder": "e.g., Parts Warehouse Inc.",
    
    // Spare Part Orders
    "orders.title": "Spare Part Orders",
    "orders.viewOrders": "View Orders",
    "orders.placeOrder": "Place Order",
    "orders.reviewOrder": "Review Order",
    "orders.editOrder": "Edit Order",
    "orders.updateOrder": "Update Order",
    "orders.review": "Review",
    "orders.searchEquipment": "Search Equipment",
    "orders.searchPlaceholder": "Search by name, serial number, or location...",
    "orders.noEquipmentFound": "No equipment found",
    "orders.sparePartName": "Spare Part Name",
    "orders.sparePartNamePlaceholder": "Enter spare part name if needed",
    "orders.quantity": "Quantity",
    "orders.itemsSelected": "{count} item selected|{count} items selected",
    "orders.selectAtLeastOne": "Please select at least one item",
    "orders.equipment": "Equipment",
    "orders.sparePart": "Spare Part",
    "orders.requested": "Requested",
    "orders.supplied": "Supplied",
    "orders.notes": "Notes",
    "orders.notesPlaceholder": "Add any additional notes...",
    "orders.submitOrder": "Submit Order",
    "orders.submitting": "Submitting...",
    "orders.createSuccess": "Order created successfully!",
    "orders.createError": "Failed to create order",
    "orders.updateSuccess": "Order updated successfully!",
    "orders.updateError": "Failed to update order",
    "orders.noOrders": "No orders found",
    "orders.orderNumber": "Order #",
    "orders.items": "item(s)",
    "orders.supervisorNotes": "Supervisor Notes",
    "orders.technicianNotes": "Technician Notes",
    "orders.status": "Status",
    "orders.statusPendingSupervisorReview": "Pending Supervisor Review",
    "orders.statusCompleted": "Completed",
    "orders.statusApproved": "Approved",
    
    // Attendance
    "attendance.title": "Attendance",
    "attendance.checkIn": "Check In",
    "attendance.checkOut": "Check Out",
    "attendance.viewRecords": "View Records",
    "attendance.logIn": "Log In",
    "attendance.logOut": "Log Out",
    "attendance.loggedInSuccess": "Logged in successfully",
    "attendance.loggedOutSuccess": "Logged out successfully",
    "attendance.logInError": "Failed to log in",
    "attendance.logOutError": "Failed to log out",
    "attendance.noPermission": "You do not have permission to view attendance records.",
    "attendance.print": "Print",
    "attendance.load": "Load",
    "attendance.report": "Attendance Report",
    "attendance.date": "Date",
    "attendance.noRecords": "No attendance records found for {date}",
    "attendance.name": "Name",
    "attendance.employeeId": "Employee ID",
    "attendance.logInTime": "Log In Time",
    "attendance.logOutTime": "Log Out Time",
    "attendance.signature": "Signature",
    "attendance.loadError": "Error loading attendance",
    
    // Common Actions
    "common.edit": "Edit",
    "common.delete": "Delete",
    "common.cancel": "Cancel",
    "common.save": "Save",
    "common.add": "Add",
    "common.create": "Create",
    "common.update": "Update",
    "common.confirm": "Confirm",
    "common.search": "Search",
    "common.filter": "Filter",
    "common.loading": "Loading...",
    "common.error": "Error",
    "common.success": "Success",
    "common.yes": "Yes",
    "common.no": "No",
    "common.searching": "Searching...",
    "common.results": "result|results",
    "common.noEquipmentFound": "No equipment found.",
    "common.searchPlaceholder": "Search equipment by name, tag number, or location",
    "common.open": "Open",
    "common.selectEquipment": "Select Equipment",
    "common.filterPlaceholder": "Type to filter by name or serial number...",
    "common.optional": "Optional",
    "common.next": "Next",
    "common.back": "Back",
    "common.refresh": "Refresh",
    "common.saving": "Saving...",

    // Dashboard Cards
    "dashboard.addEquipment": "Add Equipment/Device",
    "dashboard.addEquipmentDesc": "Register new devices into the system.",
    "dashboard.inventory": "Inventory",
    "dashboard.inventoryDesc": "View and manage all available equipment.",
    "dashboard.spareParts": "Spare Parts",
    "dashboard.sparePartsDesc": "Manage inventory of spare parts.",
    "dashboard.maintenanceSchedule": "Maintenance Schedule Preview",
    "dashboard.maintenanceScheduleDesc": "Check upcoming maintenance tasks.",
    "dashboard.maintenanceOverdue": "Preventive Maintenance",
    "dashboard.maintenanceOverdueDesc": "Automated preventive maintenance requests.",
    "dashboard.jobOrder": "Job Order",
    "dashboard.jobOrderDesc": "Submit a new support or service request.",

    // Theme
    "theme.light": "Light",
    "theme.dark": "Dark",
    "theme.system": "System",

    // Monthly Reports
    "reports.title": "Monthly Reports",
    "reports.subtitle": "Generate and view monthly reports",
    "reports.generate": "Generate Report",
    "reports.generating": "Generating...",
    "reports.month": "Month",
    "reports.year": "Year",
    "reports.location": "Location (Optional)",
    "reports.allLocations": "All locations",
    "reports.selectMonth": "Select month",
    "reports.selectYear": "Select year",
    "reports.reportPeriod": "Report Period",
    "reports.exportPDF": "Export PDF",
    "reports.print": "Print",
    "reports.generatedOn": "Generated on {date} by {user}",
    
    // Report Header
    "reports.header.title": "Monthly Report - {month} {year}",
    "reports.header.location": "Location: {campus} - {name}",
    
    // Summary Cards
    "reports.summary.equipment": "Equipment",
    "reports.summary.serviceRequests": "Service Requests",
    "reports.summary.jobOrders": "Job Orders",
    "reports.summary.totalCost": "Total Cost",
    "reports.summary.technicians": "Technicians",
    
    // Equipment Statistics
    "reports.equipment.title": "Equipment Statistics",
    "reports.equipment.byStatus": "Equipment by Status",
    "reports.equipment.newThisMonth": "New This Month",
    "reports.equipment.maintenanceDue": "Maintenance Due",
    "reports.equipment.topManufacturers": "Top Manufacturers",
    
    // Service Requests Analysis
    "reports.serviceRequests.title": "Service Requests Analysis",
    "reports.serviceRequests.overview": "Service Requests Overview",
    "reports.serviceRequests.totalRequests": "Total Requests",
    "reports.serviceRequests.totalRequestsLabel": "total requests",
    "reports.serviceRequests.byType": "Service Requests by Type",
    "reports.serviceRequests.completed": "Completed",
    "reports.serviceRequests.pending": "Pending",
    "reports.serviceRequests.inProgress": "In Progress",
    "reports.serviceRequests.successRate": "Success Rate",
    "reports.serviceRequests.requestTypes": "Request Types",
    "reports.serviceRequests.mostCommon": "Most common",
    "reports.serviceRequests.requests": "requests",
    "reports.serviceRequests.priorityLevels": "Priority Levels",
    "reports.serviceRequests.distributionUrgency": "Distribution of request urgency",
    "reports.serviceRequests.averageResponseTime": "Average Response Time",
    "reports.serviceRequests.fromRequestToCompletion": "From request to completion",
    "reports.serviceRequests.partsCost": "Parts Cost",
    "reports.serviceRequests.sparePartsUsedThisMonth": "Spare parts used this month",
    "reports.serviceRequests.averageCompletionTime": "Average Completion Time",
    "reports.serviceRequests.totalSparePartsCost": "Total Spare Parts Cost",
    "reports.serviceRequests.hours": "hours",
    
    // Job Orders Summary
    "reports.jobOrders.title": "Job Orders Summary",
    "reports.jobOrders.totalOrders": "Total Orders",
    "reports.jobOrders.equipmentItems": "Equipment Items",
    "reports.jobOrders.activeSublocations": "Active Sublocations",
    "reports.jobOrders.mostActiveSublocations": "Most Active Sublocations",
    "reports.jobOrders.orders": "orders",
    
    // Spare Parts Section
    "reports.spareParts.inventory": "Spare Parts Inventory",
    "reports.spareParts.orders": "Spare Part Orders",
    "reports.spareParts.activity": "Spare Parts Activity",
    "reports.spareParts.partsUsed": "Parts Used",
    "reports.spareParts.ordersPlaced": "Orders Placed",
    "reports.spareParts.topRequestedParts": "Most Requested Parts",
    "reports.spareParts.quantityUsed": "Quantity Used",
    "reports.spareParts.units": "units",
    "reports.spareParts.highDemand": "High (10+ units)",
    "reports.spareParts.mediumDemand": "Medium (5-9 units)",
    "reports.spareParts.lowDemand": "Low (1-4 units)",
    "reports.spareParts.showingParts": "Showing {count} parts with usage data.",
    "reports.spareParts.scrollToSeeAllParts": "Scroll to see all parts.",
    "reports.spareParts.procurementPerformance": "Procurement Performance",
    "reports.spareParts.totalRequested": "Total Requested",
    "reports.spareParts.totalItems": "Total Items",
    "reports.spareParts.lowStock": "Low Stock",
    "reports.spareParts.monthlyUsage": "Monthly Usage",
    "reports.spareParts.itemsUsed": "Items Used",
    "reports.spareParts.cost": "Cost",
    "reports.spareParts.totalOrders": "Total Orders",
    "reports.spareParts.itemsRequested": "Items Requested",
    "reports.spareParts.processingStats": "Processing Stats",
    "reports.spareParts.avgProcessingTime": "Avg Processing Time",
    "reports.spareParts.totalCost": "Total Cost",
    "reports.spareParts.partsWithHighestUsage": "Parts with highest usage this month",
    "reports.spareParts.partsUsageSummary": "Parts Usage Summary",
    "reports.spareParts.keyMetricsForOrders": "Key metrics for spare part orders",
    "reports.spareParts.orderStatusBreakdown": "Order Status Breakdown",
    "reports.spareParts.distributionByStatus": "Distribution of spare part orders by status",
    
    // Technician Performance
    "reports.technicians.title": "Technician Performance",
    "reports.technicians.performance": "Service Request Performance",
    "reports.technicians.assigned": "Assigned",
    "reports.technicians.completed": "Completed",
    "reports.technicians.activeTechnicians": "Active Technicians",
    "reports.technicians.avgHoursPerDay": "Avg. Hours/Day",
    "reports.technicians.topPerformers": "Top Performers",
    "reports.technicians.tech": "Tech",
    "reports.technicians.techPrefix": "Tech",
    
    // Monthly Reports Page
    "reports.page.title": "Monthly Reports",
    "reports.page.subtitle": "Comprehensive analytics and insights for your equipment management",
    "reports.page.realTimeAnalytics": "Real-time Analytics",
    "reports.page.interactiveCharts": "Interactive Charts",
    "reports.page.generating": "Generating Report",
    "reports.page.generatingDesc": "Please wait while we compile your monthly analytics...",
    "reports.page.readyToGenerate": "Ready to Generate Reports",
    "reports.page.readyToGenerateDesc": "Select a month and year above to create comprehensive monthly analytics with beautiful charts and insights",
    "reports.page.equipmentAnalytics": "Equipment Analytics",
    "reports.page.serviceRequests": "Service Requests",
    "reports.page.spareParts": "Spare Parts",
    
    // PDF Export
    "pdf.title": "Monthly Report",
    "pdf.generatedOn": "Generated on {date} by {user}",
    "pdf.equipmentAdded": "Equipment Added",
    "pdf.newEquipmentThisMonth": "New equipment this month",
    "pdf.serviceRequests": "Service Requests",
    "pdf.serviceRequestsHandled": "Service requests handled",
    "pdf.jobOrders": "Job Orders",
    "pdf.jobOrdersProcessed": "Job orders processed",
    "pdf.sparePartsCost": "Spare Parts Cost",
    "pdf.totalPartsExpenditure": "Total parts expenditure",
    "pdf.technicians": "Technicians",
    "pdf.activeTechnicians": "Active technicians",
    "pdf.equipmentStatistics": "Equipment Statistics",
    "pdf.equipmentByStatus": "Equipment by Status",
    "pdf.keyMetrics": "Key Metrics",
    "pdf.newThisMonth": "New This Month",
    "pdf.maintenanceDue": "Maintenance Due",
    "pdf.maintenanceOverdue": "Maintenance Overdue",
    "pdf.equipmentWithMostServiceRequests": "Equipment with Most Service Requests",
    "pdf.highNeedsAttention": "High (70%+) - Needs immediate attention",
    "pdf.mediumMonitorClosely": "Medium (40-70%) - Monitor closely",
    "pdf.lowNormalOperation": "Low (<40%) - Normal operation",
    "pdf.equipmentRequiringFrequentService": "Equipment requiring frequent service may indicate maintenance issues or high usage patterns",
    "pdf.serviceRequestsAnalysis": "Service Requests Analysis",
    "pdf.totalRequests": "Total Requests",
    "pdf.completed": "Completed",
    "pdf.pending": "Pending",
    "pdf.completionRate": "Completion Rate",
    "pdf.byType": "By Type",
    "pdf.performanceMetrics": "Performance Metrics",
    "pdf.averageCompletionTime": "Average Completion Time",
    "pdf.totalSparePartsCost": "Total Spare Parts Cost",
    "pdf.technicianPerformance": "Technician Performance",
    "pdf.summary": "Summary",
    "pdf.averageHoursPerDay": "Average Hours/Day",
    "pdf.topPerformers": "Top Performers",
    "pdf.jobOrdersSummary": "Job Orders Summary",
    "pdf.orderStatistics": "Order Statistics",
    "pdf.totalOrders": "Total Orders",
    "pdf.equipmentItems": "Equipment Items",
    "pdf.activeSublocations": "Active Sublocations",
    "pdf.mostActiveSublocations": "Most Active Sublocations",
    "pdf.mostActiveLocations": "Most Active Locations",
    "pdf.locationsWithHighJobOrderActivity": "Locations with high job order activity",
    "pdf.sparePartsInventory": "Spare Parts & Inventory",
    "pdf.inventoryStatus": "Inventory Status",
    "pdf.totalItems": "Total Items",
    "pdf.lowStockAlerts": "Low Stock Alerts",
    "pdf.monthlyUsage": "Monthly Usage",
    "pdf.monthlyCost": "Monthly Cost",
    "pdf.sparePartOrders": "Spare Part Orders",
    "pdf.itemsRequested": "Items Requested",
    "pdf.itemsSupplied": "Items Supplied",
    "pdf.mostRequestedParts": "Most Requested Parts",
    "pdf.highDemandParts": "High-demand parts may require increased stock levels",
    "pdf.footer": "This report was generated automatically by the Equipment Management System",
    "pdf.footerSupport": "For questions or support, please contact your system administrator",
    
    // Report Components
    "reports.summary.equipmentAdded": "Equipment Added",
    "reports.summary.newEquipmentThisMonth": "New equipment this month",
    "reports.summary.serviceRequestsHandled": "Service requests handled",
    "reports.summary.jobOrdersProcessed": "Job orders processed",
    "reports.summary.sparePartsCost": "Spare Parts Cost",
    "reports.summary.totalPartsExpenditure": "Total parts expenditure",
    "reports.summary.activeTechnicians": "Active technicians",
    
    // Equipment Statistics
    "reports.equipment.activity": "Equipment Activity",
    "reports.equipment.serviceRequestRate": "Service Request Rate",
    "reports.equipment.equipmentWithMostRequests": "Equipment with Most Service Requests",
    "reports.equipment.serviceRequests": "Service Requests",
    
    // Service Requests Analysis
    "reports.serviceRequests.analysis": "Service Requests Analysis",
    "reports.serviceRequests.completionRate": "Completion Rate",
    "reports.serviceRequests.performanceMetrics": "Performance Metrics",
    
    // Job Orders Summary
    "reports.jobOrders.summary": "Job Orders Summary",
    "reports.jobOrders.jobOrders": "Job Orders",
    "reports.jobOrders.locationsServed": "Locations Served",
    
    // Spare Parts Section
    "reports.spareParts.highDemandParts": "High-demand parts may require increased stock levels",
    "reports.spareParts.scrollToSeeMore": "← Scroll to see more parts →",
    "reports.spareParts.requested": "Requested",
    "reports.spareParts.avgTime": "Avg Time",
    
    // Month Names
    "months.january": "January",
    "months.february": "February", 
    "months.march": "March",
    "months.april": "April",
    "months.may": "May",
    "months.june": "June",
    "months.july": "July",
    "months.august": "August",
    "months.september": "September",
    "months.october": "October",
    "months.november": "November",
    "months.december": "December",
    
    // Priority Levels (additional)
    "priority.med": "Med",
    
    // Service Request Types
    "serviceRequest.types.maintenance": "Maintenance",
    "serviceRequest.types.repair": "Repair",
    "serviceRequest.types.inspection": "Inspection",
    "serviceRequest.types.none": "None",
    
    // Equipment Statistics (additional)
    "reports.equipment.newEquipmentAdded": "New Equipment Added",
    "reports.equipment.equipmentServiced": "Equipment Serviced",
    "reports.equipment.equipmentWithMostServiceRequests": "Equipment with Most Service Requests",
    "reports.equipment.serviceRequestSummary": "Service Request Summary",
    "reports.equipment.highRequests": "High (3+ requests)",
    "reports.equipment.mediumRequests": "Medium (2 requests)",
    "reports.equipment.lowRequests": "Low (1 request)",
    "reports.equipment.showingEquipment": "Showing {count} equipment with service requests.",
    "reports.equipment.scrollToSeeMore": "Scroll to see all equipment.",
    "reports.equipment.currentMaintenanceStatus": "Current Maintenance Status",
    "reports.equipment.referenceOnly": "(Reference Only)",
    "reports.equipment.currentStateNote": "* Current state at time of report generation, not specific to reporting period",
    
    // Error Messages
    "errors.failedToFetchLocations": "Failed to fetch locations",
    "errors.pleaseEnterLocationName": "Please enter a location name",
    "errors.pleaseSelectCampus": "Please select a campus",
    "errors.failedToAddLocation": "Failed to add location",
    "errors.failedToDeleteLocation": "Failed to delete location",
    "errors.failedToLogIn": "Failed to log in",
    "errors.failedToLogOut": "Failed to log out",
    "errors.invalidJobOrderData": "Invalid job order data",
    "errors.failedToLoadEquipmentDetails": "Failed to load equipment details",
    "errors.pleaseSelectScheduleDate": "Please select a schedule date",
    "errors.failedToSubmitJobOrder": "Failed to submit job order",
    
    // Success Messages
    "success.locationAddedSuccessfully": "Location added successfully",
    "success.locationDeletedSuccessfully": "Location \"{name}\" deleted successfully",
    "success.loggedInSuccessfully": "Logged in successfully",
    "success.loggedOutSuccessfully": "Logged out successfully",
    
    // Time Labels
    "time.timeIn": "Time In",
    "time.timeOut": "Time Out",
    
    // Filter Actions
    "filter.showAll": "Show All",
    "filter.filter": "Filter",
    
    // Toast Messages (additional)
    "toast.created": "Created successfully",
    
    // Auth Messages
    "auth.forbidden": "You do not have permission to access this page",
  },
  ar: {
    // Table
    "table.toggleDetails": "تبديل التفاصيل",
    // Common
    "common.noResults": "لا توجد نتائج",

    // Header
    "header.title": "جامعة حائل",
    "header.subtitle": "لوحة متابعة أجهزة طبية",
    "header.department": "قسم الصيانة",
    "header.facility": "إدارة المرافق",
    
    // Equipment Card
    "equipment.name": "الاسم",
    "equipment.label": "المعدات/الجهاز",
    "equipment.upToDate": "محدث",
    "equipment.dueSoon": "مستحق قريباً",
    "equipment.overdue": "متأخر",
    "equipment.lastMaintenance": "آخر صيانة",
    "equipment.nextMaintenance": "الصيانة القادمة",
    "equipment.location": "الموقع",
    "equipment.inDays": "خلال {days} أيام",
    "equipment.overdueBy": "متأخر بـ {days} أيام",
    "equipment.every": "كل",
    "equipment.sparePartsRequired": "قطع غيار مطلوبة",
    "equipment.approved": "معتمد",
    "equipment.pendingApproval": "في انتظار الموافقة",
    "equipment.requestApproval": "طلب موافقة",
    "equipment.scheduleMaintenance": "جدولة الصيانة",
    "equipment.part": "الجزء",
    "equipment.edit": "تعديل",
    "equipment.inUse": "في الاستخدام",
    "equipment.notInUse": "غير في الاستخدام",
    "equipment.status": "الحالة",
    "equipment.markMaintenanceCompleted": "تم إنهاء الصيانة",
    "equipment.equipmentUpdated": "تم تحديث المعدة",
    "equipment.delete": "حذف",
    "equipment.deleteTitle": "حذف المعدة؟",
    "equipment.deleteDescription": "سيتم إزالة {name} من القائمة.",
    "equipment.noMaintenanceSchedule": "لا يوجد جدول صيانة",

    // Add Equipment Form
    "form.addNewEquipment": "إضافة معدة جديدة",
    "form.machineName": "اسم الماكينة",
    "form.partNumber": "رقم الجزء",
    "form.location": "الموقع",
    "form.maintenanceInterval": "فترة الصيانة",
    "form.lastMaintenanceDate": "تاريخ آخر صيانة",
    "form.sparePartsRequired": "قطع غيار مطلوبة للصيانة",
    "form.selectInterval": "اختر الفترة",
    "form.everyWeek": "كل أسبوع",
    "form.every2Weeks": "كل أسبوعين",
    "form.everyMonth": "كل شهر",
    "form.every3Months": "كل 3 أشهر",
    "form.every6Months": "كل 6 أشهر", 
    "form.everyYear": "كل سنة",
    "form.addEquipment": "إضافة معدة",
    "form.cancel": "إلغاء",
    "form.required": "*",
    "form.edit": "تعديل",
    "form.save": "حفظ",
    "form.back": "رجوع",
    "form.next": "التالي",
    "form.model": "الطراز",
    "form.manufacturer": "الشركة المصنعة",
    "form.serialNumber": "الرقم التسلسلي",
    "form.status": "الحالة",
    "form.selectStatus": "اختر الحالة",
    "form.subLocation": "موقع فرعي",
    "form.newInstallation": "تثبيت جديد",
    "form.working": "عملي",
    "form.repair": "إصلاح",
    "form.maintenance": "صيانة",
    "form.partReplacement": "إستبدال القطعة",
    "form.forInstallation": "للتثبيت",

    // Alerts
    "alert.allCurrent": "جميع المعدات محدثة",
    "alert.allCurrentDesc": "جميع جداول صيانة المعدات محدثة.",
    "alert.overdueMaintenance": "صيانة متأخرة",
    "alert.overdueCount": "{count} معدة متأخرة في الصيانة.|{count} معدات متأخرة في الصيانة.",
    "alert.dueSoon": "صيانة مستحقة قريباً",
    "alert.dueSoonCount": "{count} معدة مستحقة للصيانة خلال 7 أيام.|{count} معدات مستحقة للصيانة خلال 7 أيام.",
    "alert.scheduleOverview": "نظرة عامة على جدول الصيانة",
    
    // Search and Filter
    "search.placeholder": "البحث في المعدات...",
    "filter.byStatus": "تصفية حسب الحالة",
    "filter.allEquipment": "جميع المعدات",
    "filter.upToDate": "محدث",
    "filter.dueSoon": "مستحق قريباً",
    "filter.overdue": "متأخر",
    "filter.all": "الجميع",
    "search.noResults": "لم يتم العثور على معدات تطابق معاييرك.",
    // CSV
    "csv.export": "تصدير CSV",
    "csv.import": "استيراد CSV",
    "csv.importing": "جارٍ الاستيراد...",
    "csv.imported": "تم استيراد CSV بنجاح",
    "csv.noRows": "لا توجد بيانات في ملف CSV",
    "csv.missingHeaders": "حقول إلزامية مفقودة: {missing}",
    "csv.downloadTemplate": "تحميل القالب",
    "csv.templateDownloaded": "تم تحميل القالب بنجاح",
    // List label
    "list.label.showing": "عرض {from}-{to} من {total}",
    "list.label.filteredBy": "مفلترة حسب",
    "list.label.search": "بحث \"{q}\"",
    "list.label.status": "الحالة: {status}",
    "list.label.and": "و",
    
    // Toast Messages
    "toast.error": "خطأ",
    "toast.fillRequired": "يرجى ملء جميع الحقول المطلوبة",
    "toast.success": "نجح",
    "toast.equipmentAdded": "تم إضافة المعدة بنجاح",
    "toast.equipmentUpdated": "تم تحديث المعدة بنجاح",
    "toast.maintenanceScheduled": "تم جدولة الصيانة",
    "toast.maintenanceScheduledDesc": "تم جدولة الصيانة لـ {name}.",
    "toast.serviceRequestCreated": "تم إنشاء طلب الخدمة",
    "toast.serviceRequestUpdated": "تم تحديث طلب الخدمة",
    "toast.updated": "تم التحديث بنجاح",
    
    // Language
    "language.switch": "English",
    "language.current": "العربية",
    
    // Auth
    "auth.signOut": "تسجيل الخروج",
    "auth.brand.title": "جامعة حائل",
    "auth.brand.subtitle": "نظام صيانة المعدات",
    "auth.signup.title": "أنشئ حسابك",
    "auth.signup.name": "الاسم الكامل",
    "auth.signup.name.placeholder": "مثال: جين دو",
    "auth.signup.email": "البريد الإلكتروني",
    "auth.signup.email.placeholder": "you@example.com",
    "auth.signup.password": "كلمة المرور",
    "auth.signup.password.placeholder": "••••••••",
    "auth.signup.password.helper": "ثمانية أحرف على الأقل وتتضمن حرفاً ورقماً ورمزاً خاصاً.",
    "auth.signup.confirm": "تأكيد كلمة المرور",
    "auth.signup.confirm.placeholder": "••••••••",
    "auth.signup.submit": "إنشاء الحساب",
    "auth.signup.haveAccount": "لديك حساب بالفعل؟",
    "auth.signup.signIn": "تسجيل الدخول",
    "auth.error.nameEmailRequired": "يرجى إدخال الاسم والبريد الإلكتروني",
    "auth.error.passwordConfirmRequired": "يرجى إدخال كلمة المرور وتأكيدها",
    "auth.error.passwordsNoMatch": "كلمتا المرور غير متطابقتين",
    "auth.error.passwordWeak": "يجب أن تكون كلمة المرور 8+ أحرف وتتضمن حرفاً ورقماً ورمزاً خاصاً",
    "auth.success.accountCreated": "تم إنشاء الحساب. يرجى تسجيل الدخول.",
    "auth.pendingApprovalTitle": "الحساب بانتظار الموافقة",
    "auth.pendingApprovalDesc": "تم إنشاء حسابك وهو بانتظار الموافقة. يرجى التواصل مع المشرف أو المسؤول لتفعيل الوصول.",
    "priority.low": "منخفضة",
    "priority.medium": "متوسطة",
    "priority.high": "عالية",
    "priority.urgent": "عاجلة",
    
    // Service Request Status Labels
    "serviceRequest.needsApproval": "يحتاج موافقة",
    "serviceRequest.awaitingApproval": "بانتظار الموافقة",
    "serviceRequest.overdue": "متأخر",

    // Service Request
    "serviceRequest.title": "طلب خدمة",
    "serviceRequest.manage": "إدارة",
    "serviceRequest.manageRequests": "إدارة طلبات الخدمة",
    "serviceRequest.newRequest": "إنشاء طلب خدمة",
    "serviceRequest.createTitle": "إنشاء طلب خدمة",
    "serviceRequest.editTitle": "تعديل طلب الخدمة",
    "serviceRequest.description": "املأ التفاصيل أدناه لإنشاء طلب خدمة.",
    "serviceRequest.basic": "الأساسي",
    "serviceRequest.details": "تفاصيل الفني",
    "serviceRequest.requestType": "نوع الطلب",
    "serviceRequest.selectType": "اختر النوع",
    "serviceRequest.types.preventive": "صيانة وقائية",
    "serviceRequest.types.corrective": "صيانة علاجية",
    "serviceRequest.types.install": "تركيب",
    "serviceRequest.types.assess": "تقييم",
    "serviceRequest.types.other": "أخرى",
    "serviceRequest.priority": "الأولوية",
    "serviceRequest.selectPriority": "اختر الأولوية",
    "serviceRequest.priorities.low": "منخفضة",
    "serviceRequest.priorities.medium": "متوسطة",
    "serviceRequest.priorities.high": "عالية",
    "serviceRequest.scheduledAt": "التاريخ/الوقت المجدول",
    "serviceRequest.problemDescription": "وصف المشكلة",
    "serviceRequest.problemPlaceholder": "صف المشكلة...",
    "serviceRequest.technicalAssessment": "التقييم الفني",
    "serviceRequest.assessmentPlaceholder": "أدخل التقييم الفني...",
    "serviceRequest.recommendation": "التوصية",
    "serviceRequest.recommendationPlaceholder": "أدخل التوصية...",
    "serviceRequest.viewEquipment": "عرض المعدة",
    "serviceRequest.status": "الحالة",
    "serviceRequest.approvalStatus": "حالة الموافقة",
    "serviceRequest.workStatus": "الحالة التشغيلية",
    "serviceRequest.operational.status": "الحالة التشغيلية",
    "serviceRequest.operational.operational": "تشغيلي",
    "serviceRequest.operational.underRepair": "قيد الإصلاح، بانتظار قطع الغيار",
    "serviceRequest.operational.select": "اختر الحالة التشغيلية",
    "serviceRequest.statuses.pending": "بانتظار",
    "serviceRequest.statuses.approved": "معتمد",
    "serviceRequest.statuses.rejected": "مرفوض",
    "serviceRequest.statuses.completed": "مكتمل",
    "serviceRequest.statuses.cancelled": "ملغي",
    "serviceRequest.create": "إنشاء الطلب",
    "serviceRequest.addDetails": "إضافة التفاصيل",
    "serviceRequest.detailsPendingTitle": "تفاصيل الفني قيد الإكمال",
    "serviceRequest.detailsPendingDesc": "أكمل التقييم الفني، التوصية وقطع الغيار.",
    "serviceRequest.openRequest": "طلب مفتوح",
    "serviceRequest.view": "عرض",
    "serviceRequest.selectTechnician": "اختر الفني",
    "serviceRequest.assignedTechnician": "الفني",
    "serviceRequest.assignedToMe": "معين لي",
    "serviceRequest.none": "لا يوجد",

    // Spare parts in Service Request
    "serviceRequest.spareParts.title": "قطع الغيار",
    "serviceRequest.spareParts.part": "اسم القطعة",
    "serviceRequest.spareParts.description": "الوصف (اختياري)",
    "serviceRequest.spareParts.quantity": "الكمية",
    "serviceRequest.spareParts.cost": "التكلفة",
    "serviceRequest.spareParts.source": "المصدر/المورّد",
    "serviceRequest.spareParts.add": "إضافة",
    "serviceRequest.spareParts.remove": "إزالة",
    "serviceRequest.spareParts.empty": "لم تتم إضافة قطع غيار.",
    "serviceRequest.spareParts.total": "الإجمالي: {amount}",
    "serviceRequest.spareParts.validation": "يرجى إدخال اسم القطعة والكمية",
    "serviceRequest.ticketId": "رقم التذكرة",
    "serviceRequest.stats.total": "الإجمالي",
    "serviceRequest.stats.preventive": "الصيانة الوقائية",
    "serviceRequest.stats.corrective": "الصيانة التصحيحية",
    "serviceRequest.stats.install": "التركيب",
    "serviceRequest.stats.assess": "التقييم",
    "serviceRequest.stats.other": "أخرى",
    "serviceRequest.stats.assignedToMe": "المُسندة لي",

    // Users
    "users.title": "المستخدمين",
    "users.role": "الدور",
    "users.email": "البريد الإلكتروني",
    "users.displayName": "الاسم المعروض",
    "users.create": "إنشاء",
    "users.passwordSetupNote": "بعد إنشاء مستخدم بدون كلمة مرور، شارك رابط إعداد كلمة المرور:",
    "users.copyLink": "نسخ الرابط",
    "users.copied": "تم نسخ الرابط",
    "users.copyError": "تعذر نسخ الرابط",

    // Settings
    "settings.title": "الإعدادات",
    "settings.subtitle": "إدارة الحساب والتفضيلات والمظهر.",
    "settings.account": "الحساب",
    "settings.email": "البريد الإلكتروني",
    "settings.displayName": "الاسم المعروض",
    "settings.phone": "رقم الهاتف",
    "settings.phonePlaceholder": "مثال: +966 5XXXXXXXX",
    "settings.designation": "المسمى الوظيفي",
    "settings.designationPlaceholder": "مثال: مهندس أجهزة طبية",
    "settings.department": "القسم",
    "settings.departmentPlaceholder": "مثال: الصيانة",
    "settings.resetPassword": "إعادة تعيين كلمة المرور",
    "settings.saving": "جارٍ الحفظ...",
    "settings.save": "حفظ التغييرات",
    "settings.appearance": "المظهر",
    "settings.theme": "السمة",
    "settings.themeQuick": "سمة سريعة",
    "settings.themeHint": "اختر فاتحًا أو داكنًا أو النظام",
    "settings.language": "اللغة",
    "settings.selectLanguage": "اختر اللغة",
    
    // Sidebar
    "sidebar.menu": "القائمة",
    "sidebar.home": "الرئيسية",
    "sidebar.inventory": "المخزون",
    "sidebar.locations": "المواقع",
    "sidebar.jobOrders": "أوامر العمل",
    "sidebar.serviceRequests": "طلبات الخدمة",
    "sidebar.preventiveMaintenance": "الصيانة الوقائية",
    "sidebar.reports": "التقارير",
    "sidebar.manageUsers": "إدارة المستخدمين",
    "sidebar.accountSettings": "الحساب / الإعدادات",

    // Locations
    "locations.title": "المواقع",
    "locations.subtitle": "إدارة المواقع عبر جميع الحرم الجامعي",
    "locations.addLocation": "إضافة موقع جديد",
    "locations.campus": "الحرم الجامعي",
    "locations.locationName": "اسم الموقع",
    "locations.selectCampus": "اختر الحرم الجامعي",
    "locations.enterName": "مثال: مبنى الهندسة",
    "locations.addButton": "إضافة موقع",
    "locations.allLocations": "جميع المواقع",
    "locations.showAll": "عرض جميع المواقع",
    "locations.noLocations": "لم تتم إضافة أي مواقع بعد",
    "locations.noLocationsFiltered": "لم يتم العثور على مواقع لـ {campus}",
    "locations.addFirst": "أضف موقعك الأول أعلاه",
    "locations.delete": "حذف الموقع",
    "locations.deleteConfirm": "هل أنت متأكد أنك تريد حذف \"{name}\"؟ لا يمكن التراجع عن هذا الإجراء.",
    "locations.deleteSuccess": "تم حذف الموقع بنجاح",
    "locations.viewEquipment": "عرض المعدات لهذا الموقع",
    "locations.equipmentItems": "عناصر المعدات",
    "locations.workingEquipment": "المعدات العاملة",
    "locations.noEquipment": "لا توجد معدات في هذا الموقع بعد",
    "locations.equipmentWillAppear": "ستظهر المعدات هنا بمجرد إضافتها",
    "locations.general": "عام",

    // Job Orders
    "jobOrders.title": "أوامر العمل",
    "jobOrders.subtitle": "إدارة أوامر العمل وطلبات الخدمة",

    // Dashboard
    "dashboard.locations": "المواقع",
    "dashboard.locationsDesc": "إدارة مواقع الحرم الجامعي وعرض توزيع المعدات",
    "dashboard.jobOrders": "أوامر العمل",
    "dashboard.jobOrdersDesc": "إنشاء أوامر عمل لصيانة المعدات وطلبات الخدمة",

    // Spare Parts
    "spareParts.title": "قطع الغيار",
    "spareParts.addSparePart": "إضافة قطعة غيار",
    "spareParts.name": "الاسم",
    "spareParts.serialNumber": "الرقم التسلسلي",
    "spareParts.quantity": "الكمية",
    "spareParts.manufacturer": "الشركة المصنعة",
    "spareParts.supplier": "المورّد",
    "spareParts.noResults": "لم يتم العثور على قطع غيار.",
    "spareParts.deleteTitle": "حذف قطعة الغيار",
    "spareParts.deleteDescription": "هل أنت متأكد من حذف \"{name}\"؟ لا يمكن التراجع عن هذا الإجراء.",
    "spareParts.addSuccess": "تم إضافة قطعة الغيار بنجاح!",
    "spareParts.updateSuccess": "تم تحديث قطعة الغيار بنجاح!",
    "spareParts.deleteSuccess": "تم حذف قطعة الغيار بنجاح!",
    "spareParts.addError": "فشل في إضافة قطعة الغيار",
    "spareParts.updateError": "فشل في تحديث قطعة الغيار",
    "spareParts.deleteError": "فشل في حذف قطعة الغيار",
    "spareParts.nameRequired": "الاسم مطلوب",
    "spareParts.adding": "جارٍ الإضافة...",
    "spareParts.deleteConfirm": "هل أنت متأكد من حذف قطعة الغيار؟",
    "spareParts.namePlaceholder": "مثال: فلتر هواء",
    "spareParts.serialNumberPlaceholder": "مثال: SN-12345",
    "spareParts.quantityPlaceholder": "مثال: 10",
    "spareParts.manufacturerPlaceholder": "مثال: شركة أكمي",
    "spareParts.supplierPlaceholder": "مثال: مستودع القطع",
    
    // Spare Part Orders
    "orders.title": "طلبات قطع الغيار",
    "orders.viewOrders": "عرض الطلبات",
    "orders.placeOrder": "تقديم طلب",
    "orders.reviewOrder": "مراجعة الطلب",
    "orders.editOrder": "تعديل الطلب",
    "orders.updateOrder": "تحديث الطلب",
    "orders.review": "مراجعة",
    "orders.searchEquipment": "البحث عن المعدات",
    "orders.searchPlaceholder": "البحث بالاسم أو الرقم التسلسلي أو الموقع...",
    "orders.noEquipmentFound": "لم يتم العثور على معدات",
    "orders.sparePartName": "اسم قطعة الغيار",
    "orders.sparePartNamePlaceholder": "أدخل اسم قطعة الغيار إذا لزم الأمر",
    "orders.quantity": "الكمية",
    "orders.itemsSelected": "تم تحديد {count} عنصر|تم تحديد {count} عناصر",
    "orders.selectAtLeastOne": "الرجاء تحديد عنصر واحد على الأقل",
    "orders.equipment": "المعدات",
    "orders.sparePart": "قطعة الغيار",
    "orders.requested": "المطلوب",
    "orders.supplied": "الموردة",
    "orders.notes": "ملاحظات",
    "orders.notesPlaceholder": "أضف أي ملاحظات إضافية...",
    "orders.submitOrder": "إرسال الطلب",
    "orders.submitting": "جارٍ الإرسال...",
    "orders.createSuccess": "تم إنشاء الطلب بنجاح!",
    "orders.createError": "فشل في إنشاء الطلب",
    "orders.updateSuccess": "تم تحديث الطلب بنجاح!",
    "orders.updateError": "فشل في تحديث الطلب",
    "orders.noOrders": "لا توجد طلبات",
    "orders.orderNumber": "طلب #",
    "orders.items": "عنصر",
    "orders.supervisorNotes": "ملاحظات المشرف",
    "orders.technicianNotes": "ملاحظات الفني",
    "orders.status": "الحالة",
    "orders.statusPendingSupervisorReview": "في انتظار مراجعة المشرف",
    "orders.statusCompleted": "مكتمل",
    "orders.statusApproved": "معتمد",
    
    // Attendance
    "attendance.title": "الحضور",
    "attendance.checkIn": "تسجيل الدخول",
    "attendance.checkOut": "تسجيل الخروج",
    "attendance.viewRecords": "عرض السجلات",
    "attendance.logIn": "تسجيل الدخول",
    "attendance.logOut": "تسجيل الخروج",
    "attendance.loggedInSuccess": "تم تسجيل الدخول بنجاح",
    "attendance.loggedOutSuccess": "تم تسجيل الخروج بنجاح",
    "attendance.logInError": "فشل تسجيل الدخول",
    "attendance.logOutError": "فشل تسجيل الخروج",
    "attendance.noPermission": "ليس لديك صلاحية عرض سجلات الحضور.",
    "attendance.print": "طباعة",
    "attendance.load": "تحميل",
    "attendance.report": "تقرير الحضور",
    "attendance.date": "التاريخ",
    "attendance.noRecords": "لم يتم العثور على سجلات حضور لتاريخ {date}",
    "attendance.name": "الاسم",
    "attendance.employeeId": "رقم الموظف",
    "attendance.logInTime": "وقت الدخول",
    "attendance.logOutTime": "وقت الخروج",
    "attendance.signature": "التوقيع",
    "attendance.loadError": "خطأ في تحميل الحضور",
    
    // Common Actions
    "common.edit": "تعديل",
    "common.delete": "حذف",
    "common.cancel": "إلغاء",
    "common.save": "حفظ",
    "common.add": "إضافة",
    "common.create": "إنشاء",
    "common.update": "تحديث",
    "common.confirm": "تأكيد",
    "common.search": "بحث",
    "common.filter": "تصفية",
    "common.loading": "جارٍ التحميل...",
    "common.error": "خطأ",
    "common.success": "نجح",
    "common.yes": "نعم",
    "common.no": "لا",
    "common.searching": "جارٍ البحث...",
    "common.results": "نتيجة|نتائج",
    "common.noEquipmentFound": "لم يتم العثور على معدات.",
    "common.searchPlaceholder": "بحث في المعدات حسب الاسم أو الرقم أو الموقع",
    "common.open": "فتح",
    "common.selectEquipment": "اختر المعدة",
    "common.filterPlaceholder": "اكتب للتصفية حسب الاسم أو الرقم التسلسلي...",
    "common.optional": "اختياري",
    "common.next": "التالي",
    "common.back": "رجوع",
    "common.refresh": "تحديث",
    "common.saving": "جارٍ الحفظ...",

    // Dashboard Cards
    "dashboard.addEquipment": "إضافة معدة/جهاز",
    "dashboard.addEquipmentDesc": "تسجيل أجهزة جديدة في النظام.",
    "dashboard.inventory": "المخزون",
    "dashboard.inventoryDesc": "عرض وإدارة جميع المعدات المتوفرة.",
    "dashboard.spareParts": "قطع الغيار",
    "dashboard.sparePartsDesc": "إدارة مخزون قطع الغيار.",
    "dashboard.maintenanceSchedule": "معاينة جدول الصيانة",
    "dashboard.maintenanceScheduleDesc": "تحقق من مهام الصيانة القادمة.",
    "dashboard.maintenanceOverdue": "صيانة متأخرة",
    "dashboard.maintenanceOverdueDesc": "عرض الأجهزة ذات الصيانة المتأخرة.",
    "dashboard.jobOrder": "طلب عمل",
    "dashboard.jobOrderDesc": "تقديم طلب دعم أو خدمة جديد.",

    // Theme
    "theme.light": "فاتح",
    "theme.dark": "داكن",
    "theme.system": "النظام",

    // Monthly Reports
    "reports.title": "التقارير الشهرية",
    "reports.subtitle": "إنشاء وعرض التقارير الشهرية",
    "reports.generate": "إنشاء التقرير",
    "reports.generating": "جارٍ الإنشاء...",
    "reports.month": "الشهر",
    "reports.year": "السنة",
    "reports.location": "الموقع (اختياري)",
    "reports.allLocations": "جميع المواقع",
    "reports.selectMonth": "اختر الشهر",
    "reports.selectYear": "اختر السنة",
    "reports.reportPeriod": "فترة التقرير",
    "reports.exportPDF": "تصدير PDF",
    "reports.print": "طباعة",
    "reports.generatedOn": "تم إنشاؤه في {date} بواسطة {user}",
    
    // Report Header
    "reports.header.title": "التقرير الشهري - {month} {year}",
    "reports.header.location": "الموقع: {campus} - {name}",
    
    // Summary Cards
    "reports.summary.equipment": "المعدات",
    "reports.summary.serviceRequests": "طلبات الخدمة",
    "reports.summary.jobOrders": "أوامر العمل",
    "reports.summary.totalCost": "التكلفة الإجمالية",
    "reports.summary.technicians": "الفنيين",
    
    // Equipment Statistics
    "reports.equipment.title": "إحصائيات المعدات",
    "reports.equipment.byStatus": "المعدات حسب الحالة",
    "reports.equipment.newThisMonth": "جديد هذا الشهر",
    "reports.equipment.maintenanceDue": "الصيانة مستحقة",
    "reports.equipment.topManufacturers": "أفضل الشركات المصنعة",
    
    // Service Requests Analysis
    "reports.serviceRequests.title": "تحليل طلبات الخدمة",
    "reports.serviceRequests.overview": "نظرة عامة على طلبات الخدمة",
    "reports.serviceRequests.totalRequests": "إجمالي الطلبات",
    "reports.serviceRequests.totalRequestsLabel": "إجمالي الطلبات",
    "reports.serviceRequests.byType": "طلبات الخدمة حسب النوع",
    "reports.serviceRequests.completed": "مكتمل",
    "reports.serviceRequests.pending": "في الانتظار",
    "reports.serviceRequests.inProgress": "قيد التنفيذ",
    "reports.serviceRequests.successRate": "معدل النجاح",
    "reports.serviceRequests.requestTypes": "أنواع الطلبات",
    "reports.serviceRequests.mostCommon": "الأكثر شيوعاً",
    "reports.serviceRequests.requests": "طلبات",
    "reports.serviceRequests.priorityLevels": "مستويات الأولوية",
    "reports.serviceRequests.distributionUrgency": "توزيع إلحاح الطلبات",
    "reports.serviceRequests.averageResponseTime": "متوسط وقت الاستجابة",
    "reports.serviceRequests.fromRequestToCompletion": "من الطلب إلى الإنجاز",
    "reports.serviceRequests.partsCost": "تكلفة القطع",
    "reports.serviceRequests.sparePartsUsedThisMonth": "قطع الغيار المستخدمة هذا الشهر",
    "reports.serviceRequests.averageCompletionTime": "متوسط وقت الإنجاز",
    "reports.serviceRequests.totalSparePartsCost": "إجمالي تكلفة قطع الغيار",
    "reports.serviceRequests.hours": "ساعات",
    
    // Job Orders Summary
    "reports.jobOrders.title": "ملخص أوامر العمل",
    "reports.jobOrders.totalOrders": "إجمالي الطلبات",
    "reports.jobOrders.equipmentItems": "عناصر المعدات",
    "reports.jobOrders.activeSublocations": "المواقع الفرعية النشطة",
    "reports.jobOrders.mostActiveSublocations": "المواقع الفرعية الأكثر نشاطاً",
    "reports.jobOrders.orders": "طلبات",
    
    // Spare Parts Section
    "reports.spareParts.inventory": "مخزون قطع الغيار",
    "reports.spareParts.orders": "طلبات قطع الغيار",
    "reports.spareParts.activity": "نشاط قطع الغيار",
    "reports.spareParts.partsUsed": "القطع المستخدمة",
    "reports.spareParts.ordersPlaced": "الطلبات المقدمة",
    "reports.spareParts.topRequestedParts": "القطع الأكثر طلباً",
    "reports.spareParts.quantityUsed": "الكمية المستخدمة",
    "reports.spareParts.units": "وحدات",
    "reports.spareParts.highDemand": "عالية (10+ وحدات)",
    "reports.spareParts.mediumDemand": "متوسطة (5-9 وحدات)",
    "reports.spareParts.lowDemand": "منخفضة (1-4 وحدات)",
    "reports.spareParts.showingParts": "عرض {count} قطع مع بيانات الاستخدام.",
    "reports.spareParts.scrollToSeeAllParts": "مرر لرؤية جميع القطع.",
    "reports.spareParts.procurementPerformance": "أداء المشتريات",
    "reports.spareParts.totalRequested": "إجمالي المطلوب",
    "reports.spareParts.totalItems": "إجمالي العناصر",
    "reports.spareParts.lowStock": "مخزون منخفض",
    "reports.spareParts.monthlyUsage": "الاستخدام الشهري",
    "reports.spareParts.itemsUsed": "العناصر المستخدمة",
    "reports.spareParts.cost": "التكلفة",
    "reports.spareParts.totalOrders": "إجمالي الطلبات",
    "reports.spareParts.itemsRequested": "العناصر المطلوبة",
    "reports.spareParts.processingStats": "إحصائيات المعالجة",
    "reports.spareParts.avgProcessingTime": "متوسط وقت المعالجة",
    "reports.spareParts.totalCost": "التكلفة الإجمالية",
    "reports.spareParts.partsWithHighestUsage": "القطع ذات أعلى استخدام هذا الشهر",
    "reports.spareParts.partsUsageSummary": "ملخص استخدام القطع",
    "reports.spareParts.keyMetricsForOrders": "المقاييس الرئيسية لطلبات قطع الغيار",
    "reports.spareParts.orderStatusBreakdown": "تفصيل حالة الطلبات",
    "reports.spareParts.distributionByStatus": "توزيع طلبات قطع الغيار حسب الحالة",
    
    // Technician Performance
    "reports.technicians.title": "أداء الفنيين",
    "reports.technicians.performance": "أداء طلبات الخدمة",
    "reports.technicians.assigned": "مُسند",
    "reports.technicians.completed": "مكتمل",
    "reports.technicians.activeTechnicians": "الفنيين النشطين",
    "reports.technicians.avgHoursPerDay": "متوسط الساعات/اليوم",
    "reports.technicians.topPerformers": "أفضل الأداء",
    "reports.technicians.tech": "فني",
    "reports.technicians.techPrefix": "فني",
    
    // Monthly Reports Page
    "reports.page.title": "التقارير الشهرية",
    "reports.page.subtitle": "تحليلات شاملة ورؤى لإدارة معداتك",
    "reports.page.realTimeAnalytics": "تحليلات فورية",
    "reports.page.interactiveCharts": "رسوم بيانية تفاعلية",
    "reports.page.generating": "إنشاء التقرير",
    "reports.page.generatingDesc": "يرجى الانتظار بينما نقوم بتجميع تحليلاتك الشهرية...",
    "reports.page.readyToGenerate": "جاهز لإنشاء التقارير",
    "reports.page.readyToGenerateDesc": "اختر شهراً وسنة أعلاه لإنشاء تحليلات شهرية شاملة مع رسوم بيانية جميلة ورؤى",
    "reports.page.equipmentAnalytics": "تحليلات المعدات",
    "reports.page.serviceRequests": "طلبات الخدمة",
    "reports.page.spareParts": "قطع الغيار",
    
    // PDF Export
    "pdf.title": "التقرير الشهري",
    "pdf.generatedOn": "تم إنشاؤه في {date} بواسطة {user}",
    "pdf.equipmentAdded": "المعدات المضافة",
    "pdf.newEquipmentThisMonth": "معدات جديدة هذا الشهر",
    "pdf.serviceRequests": "طلبات الخدمة",
    "pdf.serviceRequestsHandled": "طلبات الخدمة المعالجة",
    "pdf.jobOrders": "أوامر العمل",
    "pdf.jobOrdersProcessed": "أوامر العمل المعالجة",
    "pdf.sparePartsCost": "تكلفة قطع الغيار",
    "pdf.totalPartsExpenditure": "إجمالي إنفاق القطع",
    "pdf.technicians": "الفنيين",
    "pdf.activeTechnicians": "الفنيين النشطين",
    "pdf.equipmentStatistics": "إحصائيات المعدات",
    "pdf.equipmentByStatus": "المعدات حسب الحالة",
    "pdf.keyMetrics": "المقاييس الرئيسية",
    "pdf.newThisMonth": "جديد هذا الشهر",
    "pdf.maintenanceDue": "الصيانة مستحقة",
    "pdf.maintenanceOverdue": "الصيانة متأخرة",
    "pdf.equipmentWithMostServiceRequests": "المعدات ذات أكبر عدد من طلبات الخدمة",
    "pdf.highNeedsAttention": "عالية (70%+) - تحتاج انتباه فوري",
    "pdf.mediumMonitorClosely": "متوسطة (40-70%) - مراقبة عن كثب",
    "pdf.lowNormalOperation": "منخفضة (<40%) - تشغيل طبيعي",
    "pdf.equipmentRequiringFrequentService": "المعدات التي تتطلب خدمة متكررة قد تشير إلى مشاكل صيانة أو أنماط استخدام عالية",
    "pdf.serviceRequestsAnalysis": "تحليل طلبات الخدمة",
    "pdf.totalRequests": "إجمالي الطلبات",
    "pdf.completed": "مكتمل",
    "pdf.pending": "في الانتظار",
    "pdf.completionRate": "معدل الإنجاز",
    "pdf.byType": "حسب النوع",
    "pdf.performanceMetrics": "مقاييس الأداء",
    "pdf.averageCompletionTime": "متوسط وقت الإنجاز",
    "pdf.totalSparePartsCost": "إجمالي تكلفة قطع الغيار",
    "pdf.technicianPerformance": "أداء الفنيين",
    "pdf.summary": "الملخص",
    "pdf.averageHoursPerDay": "متوسط الساعات/اليوم",
    "pdf.topPerformers": "أفضل الأداء",
    "pdf.jobOrdersSummary": "ملخص أوامر العمل",
    "pdf.orderStatistics": "إحصائيات الطلبات",
    "pdf.totalOrders": "إجمالي الطلبات",
    "pdf.equipmentItems": "عناصر المعدات",
    "pdf.activeSublocations": "المواقع الفرعية النشطة",
    "pdf.mostActiveSublocations": "المواقع الفرعية الأكثر نشاطاً",
    "pdf.mostActiveLocations": "المواقع الأكثر نشاطاً",
    "pdf.locationsWithHighJobOrderActivity": "المواقع ذات نشاط أوامر العمل العالي",
    "pdf.sparePartsInventory": "قطع الغيار والمخزون",
    "pdf.inventoryStatus": "حالة المخزون",
    "pdf.totalItems": "إجمالي العناصر",
    "pdf.lowStockAlerts": "تنبيهات المخزون المنخفض",
    "pdf.monthlyUsage": "الاستخدام الشهري",
    "pdf.monthlyCost": "التكلفة الشهرية",
    "pdf.sparePartOrders": "طلبات قطع الغيار",
    "pdf.itemsRequested": "العناصر المطلوبة",
    "pdf.itemsSupplied": "العناصر الموردة",
    "pdf.mostRequestedParts": "القطع الأكثر طلباً",
    "pdf.highDemandParts": "القطع عالية الطلب قد تتطلب مستويات مخزون متزايدة",
    "pdf.footer": "تم إنشاء هذا التقرير تلقائياً بواسطة نظام إدارة المعدات",
    "pdf.footerSupport": "للأسئلة أو الدعم، يرجى التواصل مع مسؤول النظام",
    
    // Report Components
    "reports.summary.equipmentAdded": "المعدات المضافة",
    "reports.summary.newEquipmentThisMonth": "معدات جديدة هذا الشهر",
    "reports.summary.serviceRequestsHandled": "طلبات الخدمة المعالجة",
    "reports.summary.jobOrdersProcessed": "أوامر العمل المعالجة",
    "reports.summary.sparePartsCost": "تكلفة قطع الغيار",
    "reports.summary.totalPartsExpenditure": "إجمالي إنفاق القطع",
    "reports.summary.activeTechnicians": "الفنيين النشطين",
    
    // Equipment Statistics
    "reports.equipment.activity": "نشاط المعدات",
    "reports.equipment.serviceRequestRate": "معدل طلبات الخدمة",
    "reports.equipment.equipmentWithMostRequests": "المعدات ذات أكبر عدد من طلبات الخدمة",
    "reports.equipment.serviceRequests": "طلبات الخدمة",
    
    // Service Requests Analysis
    "reports.serviceRequests.analysis": "تحليل طلبات الخدمة",
    "reports.serviceRequests.completionRate": "معدل الإنجاز",
    "reports.serviceRequests.performanceMetrics": "مقاييس الأداء",
    
    // Job Orders Summary
    "reports.jobOrders.summary": "ملخص أوامر العمل",
    "reports.jobOrders.jobOrders": "أوامر العمل",
    "reports.jobOrders.locationsServed": "المواقع المخدومة",
    
    // Spare Parts Section
    "reports.spareParts.highDemandParts": "القطع عالية الطلب قد تتطلب مستويات مخزون متزايدة",
    "reports.spareParts.scrollToSeeMore": "← مرر لرؤية المزيد من القطع →",
    "reports.spareParts.requested": "مطلوب",
    "reports.spareParts.avgTime": "متوسط الوقت",
    
    // Month Names
    "months.january": "يناير",
    "months.february": "فبراير",
    "months.march": "مارس",
    "months.april": "أبريل",
    "months.may": "مايو",
    "months.june": "يونيو",
    "months.july": "يوليو",
    "months.august": "أغسطس",
    "months.september": "سبتمبر",
    "months.october": "أكتوبر",
    "months.november": "نوفمبر",
    "months.december": "ديسمبر",
    
    // Priority Levels (additional)
    "priority.med": "متوسط",
    
    // Service Request Types
    "serviceRequest.types.maintenance": "صيانة",
    "serviceRequest.types.repair": "إصلاح",
    "serviceRequest.types.inspection": "فحص",
    "serviceRequest.types.none": "لا يوجد",
    
    // Equipment Statistics (additional)
    "reports.equipment.newEquipmentAdded": "معدات جديدة مضافة",
    "reports.equipment.equipmentServiced": "معدات تم صيانتها",
    "reports.equipment.equipmentWithMostServiceRequests": "المعدات ذات أكبر عدد من طلبات الخدمة",
    "reports.equipment.serviceRequestSummary": "ملخص طلبات الخدمة",
    "reports.equipment.highRequests": "عالية (3+ طلبات)",
    "reports.equipment.mediumRequests": "متوسطة (طلبين)",
    "reports.equipment.lowRequests": "منخفضة (طلب واحد)",
    "reports.equipment.showingEquipment": "عرض {count} معدات مع طلبات خدمة.",
    "reports.equipment.scrollToSeeMore": "مرر لرؤية جميع المعدات.",
    "reports.equipment.currentMaintenanceStatus": "حالة الصيانة الحالية",
    "reports.equipment.referenceOnly": "(مرجع فقط)",
    "reports.equipment.currentStateNote": "* الحالة الحالية وقت إنشاء التقرير، وليس محددة لفترة التقرير",
    
    // Error Messages
    "errors.failedToFetchLocations": "فشل في جلب المواقع",
    "errors.pleaseEnterLocationName": "يرجى إدخال اسم الموقع",
    "errors.pleaseSelectCampus": "يرجى اختيار الحرم الجامعي",
    "errors.failedToAddLocation": "فشل في إضافة الموقع",
    "errors.failedToDeleteLocation": "فشل في حذف الموقع",
    "errors.failedToLogIn": "فشل تسجيل الدخول",
    "errors.failedToLogOut": "فشل تسجيل الخروج",
    "errors.invalidJobOrderData": "بيانات أمر العمل غير صحيحة",
    "errors.failedToLoadEquipmentDetails": "فشل في تحميل تفاصيل المعدات",
    "errors.pleaseSelectScheduleDate": "يرجى اختيار تاريخ الجدولة",
    "errors.failedToSubmitJobOrder": "فشل في إرسال أمر العمل",
    
    // Success Messages
    "success.locationAddedSuccessfully": "تم إضافة الموقع بنجاح",
    "success.locationDeletedSuccessfully": "تم حذف الموقع \"{name}\" بنجاح",
    "success.loggedInSuccessfully": "تم تسجيل الدخول بنجاح",
    "success.loggedOutSuccessfully": "تم تسجيل الخروج بنجاح",
    
    // Time Labels
    "time.timeIn": "وقت الدخول",
    "time.timeOut": "وقت الخروج",
    
    // Filter Actions
    "filter.showAll": "عرض الكل",
    "filter.filter": "تصفية",
    
    // Toast Messages (additional)
    "toast.created": "تم الإنشاء بنجاح",
    
    // Auth Messages
    "auth.forbidden": "ليس لديك صلاحية للوصول إلى هذه الصفحة",
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>("en");
  
  const t = (key: string, params?: Record<string, unknown>) => {
    // Special case for getting current language code
    if (key === "lang") return language;
    
    let text = translations[language][key as keyof typeof translations[typeof language]] || key;
    
    // Handle pluralization for count
    if (params?.count !== undefined && text.includes("|")) {
      const [singular, plural] = text.split("|");
      text = params.count === 1 ? singular : plural;
    }
    
    // Replace parameters
    if (params) {
      Object.keys(params).forEach(param => {
        text = text.replace(`{${param}}`, params[param] as string);
      });
    }
    
    return text;
  };
  
  const isRTL = language === "ar";
  
  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      <div className={isRTL ? "rtl" : "ltr"} dir={isRTL ? "rtl" : "ltr"}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};

// Helper function to get all PDF translations for export
export const getPDFTranslations = (language: Language): Record<string, string> => {
  const pdfKeys = [
    "pdf.title", "pdf.generatedOn", "pdf.equipmentAdded", "pdf.newEquipmentThisMonth",
    "pdf.serviceRequests", "pdf.serviceRequestsHandled", "pdf.jobOrders", "pdf.jobOrdersProcessed",
    "pdf.sparePartsCost", "pdf.totalPartsExpenditure", "pdf.technicians", "pdf.activeTechnicians",
    "pdf.equipmentStatistics", "pdf.equipmentByStatus", "pdf.keyMetrics", "pdf.newThisMonth",
    "pdf.maintenanceDue", "pdf.maintenanceOverdue", "pdf.equipmentWithMostServiceRequests",
    "pdf.highNeedsAttention", "pdf.mediumMonitorClosely", "pdf.lowNormalOperation",
    "pdf.equipmentRequiringFrequentService", "pdf.serviceRequestsAnalysis", "pdf.totalRequests",
    "pdf.completed", "pdf.pending", "pdf.completionRate", "pdf.byType", "pdf.performanceMetrics",
    "pdf.averageCompletionTime", "pdf.totalSparePartsCost", "pdf.technicianPerformance",
    "pdf.summary", "pdf.averageHoursPerDay", "pdf.topPerformers", "pdf.jobOrdersSummary",
    "pdf.orderStatistics", "pdf.totalOrders", "pdf.equipmentItems", "pdf.activeSublocations",
    "pdf.mostActiveSublocations", "pdf.mostActiveLocations", "pdf.locationsWithHighJobOrderActivity",
    "pdf.sparePartsInventory", "pdf.inventoryStatus", "pdf.totalItems", "pdf.lowStockAlerts",
    "pdf.monthlyUsage", "pdf.monthlyCost", "pdf.sparePartOrders", "pdf.itemsRequested",
    "pdf.itemsSupplied", "pdf.mostRequestedParts", "pdf.highDemandParts", "pdf.footer",
    "pdf.footerSupport"
  ];
  
  const result: Record<string, string> = {};
  pdfKeys.forEach(key => {
    result[key] = translations[language][key as keyof typeof translations[typeof language]] || key;
  });
  
  return result;
};