'use client'
import React, { createContext, useContext, useState, ReactNode } from "react";

type Language = "en" | "ar";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, unknown>) => string;
  isRTL: boolean;
}

const translations = {
  en: {
    // Table
    "table.toggleDetails": "Toggle details",
    // Common
    "common.noResults": "No results",

    // Header
    "header.title": "University of Ha'il",
    "header.subtitle": "Biomedical Equipment Dashboard",
    "header.department": "Maintenance Department",
    "header.facility": "Facility Management",
    
    // Equipment Card
    "equipment.name": "Equipment/Device Name",
    "equipment.upToDate": "Up to Date",
    "equipment.dueSoon": "Due Soon", 
    "equipment.overdue": "Overdue",
    "equipment.lastMaintenance": "Last Maintenance",
    "equipment.nextMaintenance": "Next Maintenance",
    "equipment.location": "Location",
    "equipment.inDays": "In {days} days",
    "equipment.overdueBy": "Overdue by {days} days",
    "equipment.every": "Every",
    "equipment.sparePartsRequired": "Spare Parts Required",
    "equipment.approved": "Approved",
    "equipment.pendingApproval": "Pending Approval",
    "equipment.requestApproval": "Request Approval",
    "equipment.scheduleMaintenance": "Schedule Maintenance",
    "equipment.part": "Tag Number",
    "equipment.edit": "Edit",
    "equipment.inUse": "In Use",
    "equipment.notInUse": "Not In Use",
    "equipment.status": "Status",
    "equipment.markMaintenanceCompleted": "Mark Maintenance Completed",
    "equipment.equipmentUpdated": "Equipment Updated",
    "equipment.delete": "Delete",
    "equipment.deleteTitle": "Delete equipment?",
    "equipment.deleteDescription": "This will remove {name} from the list.",
    "equipment.noMaintenanceSchedule": "No maintenance scheduled",
    
    // Add Equipment Form
    "form.addNewEquipment": "Add New Equipment",
    "form.machineName": "Equipment/Device name",
    "form.partNumber": "Tag Number",
    "form.location": "Location",
    "form.maintenanceInterval": "Maintenance Interval",
    "form.lastMaintenanceDate": "Last Maintenance Date",
    "form.sparePartsRequired": "Spare parts required for maintenance",
    "form.selectInterval": "Select interval",
    "form.everyWeek": "Every Week",
    "form.every2Weeks": "Every 2 Weeks", 
    "form.everyMonth": "Every Month",
    "form.every3Months": "Every 3 Months",
    "form.every6Months": "Every 6 Months",
    "form.everyYear": "Every Year",
    "form.addEquipment": "Add Equipment",
    "form.cancel": "Cancel",
    "form.required": "*",
    "form.edit": "Edit",
    "form.save": "Save",
    "form.back": "Back",
    "form.next": "Next",
    "form.model": "Model",
    "form.manufacturer": "Manufacturer",
    "form.serialNumber": "Serial Number",
    "form.status": "Status",
    "form.selectStatus": "Select status",
    "form.subLocation": "Sub-location",
    "form.newInstallation": "New Installation",
    "form.working": "Working",
    "form.repair": "Repair",
    "form.maintenance": "Maintenance",
    "form.partReplacement": "Part Replacement",
    "form.forInstallation": "For Installation",
    
    // Alerts
    "alert.allCurrent": "All Equipment Current",
    "alert.allCurrentDesc": "All equipment maintenance schedules are up to date.",
    "alert.overdueMaintenance": "Overdue Maintenance",
    "alert.overdueCount": "{count} equipment item overdue for maintenance.|{count} equipment items overdue for maintenance.",
    "alert.dueSoon": "Maintenance Due Soon",
    "alert.dueSoonCount": "{count} equipment item due for maintenance within 7 days.|{count} equipment items due for maintenance within 7 days.",
    "alert.scheduleOverview": "Maintenance Schedule Overview",
    
    // Search and Filter
    "search.placeholder": "Search equipment...",
    "filter.byStatus": "Filter by status",
    "filter.allEquipment": "All Equipment",
    "filter.upToDate": "Up to Date",
    "filter.dueSoon": "Due Soon",
    "filter.overdue": "Overdue",
    "filter.all": "All",
    "search.noResults": "No equipment found matching your criteria.",
    // CSV
    "csv.export": "Export CSV",
    "csv.import": "Import CSV",
    "csv.importing": "Importing...",
    "csv.imported": "CSV imported successfully",
    "csv.noRows": "No data rows found in CSV",
    "csv.missingHeaders": "Missing required headers: {missing}",
    "csv.downloadTemplate": "Download Template",
    "csv.templateDownloaded": "Template downloaded successfully",
    // List label
    "list.label.showing": "Showing {from}-{to} of {total}",
    "list.label.filteredBy": "filtered by",
    "list.label.search": "search \"{q}\"",
    "list.label.status": "status: {status}",
    "list.label.and": "and",
    
    // Toast Messages
    "toast.error": "Error",
    "toast.fillRequired": "Please fill in all required fields",
    "toast.success": "Success", 
    "toast.equipmentAdded": "Equipment added successfully",
    "toast.equipmentUpdated": "Equipment updated successfully",
    "toast.maintenanceScheduled": "Maintenance Scheduled",
    "toast.maintenanceScheduledDesc": "Maintenance for {name} has been scheduled.",
    "toast.serviceRequestCreated": "Service request created",
    "toast.serviceRequestUpdated": "Service request updated",
    "toast.updated": "Updated successfully",
    
    // Language
    "language.switch": "العربية",
    "language.current": "English",
    
    // Auth
    "auth.signOut": "Sign out",
    "auth.brand.title": "University of Ha'il",
    "auth.brand.subtitle": "Equipment Maintenance System",
    "auth.signup.title": "Create your account",
    "auth.signup.name": "Full name",
    "auth.signup.name.placeholder": "e.g. Jane Doe",
    "auth.signup.email": "Email",
    "auth.signup.email.placeholder": "you@example.com",
    "auth.signup.password": "Password",
    "auth.signup.password.placeholder": "••••••••",
    "auth.signup.password.helper": "At least 8 characters with a letter and number.",
    "auth.signup.confirm": "Confirm password",
    "auth.signup.confirm.placeholder": "••••••••",
    "auth.signup.submit": "Create account",
    "auth.signup.haveAccount": "Already have an account?",
    "auth.signup.signIn": "Sign in",
    "auth.error.nameEmailRequired": "Please enter name and email",
    "auth.error.passwordConfirmRequired": "Please enter and confirm your password",
    "auth.error.passwordsNoMatch": "Passwords do not match",
    "auth.error.passwordWeak": "Password must be 8+ chars, include a letter and number",
    "auth.success.accountCreated": "Account created. Please sign in.",
    "auth.pendingApprovalTitle": "Account Pending Approval",
    "auth.pendingApprovalDesc": "Your account has been created and is awaiting approval. Please contact your supervisor or administrator to activate access.",
    "priority.low": "Low",
    "priority.medium": "Medium",
    "priority.high": "High",
    "priority.urgent": "Urgent",

    // Service Request
    "serviceRequest.title": "Service Request",
    "serviceRequest.manage": "Manage",
    "serviceRequest.manageRequests": "Manage Service Requests",
    "serviceRequest.newRequest": "Raise Service Request",
    "serviceRequest.createTitle": "Create Service Request",
    "serviceRequest.editTitle": "Edit Service Request",
    "serviceRequest.description": "Fill in the details below to raise a service request.",
    "serviceRequest.basic": "Basic",
    "serviceRequest.details": "Technician Details",
    "serviceRequest.requestType": "Request Type",
    "serviceRequest.selectType": "Select type",
    "serviceRequest.types.preventive": "Preventive maintenance",
    "serviceRequest.types.corrective": "Corrective maintenance",
    "serviceRequest.types.install": "Install",
    "serviceRequest.types.assess": "Assess",
    "serviceRequest.types.other": "Other",
    "serviceRequest.priority": "Priority",
    "serviceRequest.selectPriority": "Select priority",
    "serviceRequest.priorities.low": "Low",
    "serviceRequest.priorities.medium": "Medium",
    "serviceRequest.priorities.high": "High",
    "serviceRequest.scheduledAt": "Scheduled At",
    "serviceRequest.problemDescription": "Problem Description",
    "serviceRequest.problemPlaceholder": "Describe the problem...",
    "serviceRequest.technicalAssessment": "Technical Assessment",
    "serviceRequest.assessmentPlaceholder": "Enter technical assessment...",
    "serviceRequest.recommendation": "Recommendation",
    "serviceRequest.recommendationPlaceholder": "Enter recommendation...",
    "serviceRequest.viewEquipment": "View equipment",
    "serviceRequest.status": "Status",
    "serviceRequest.approvalStatus": "Approval Status",
    "serviceRequest.workStatus": "Work Status",
    "serviceRequest.statuses.pending": "Pending",
    "serviceRequest.statuses.approved": "Approved",
    "serviceRequest.statuses.rejected": "Rejected",
    "serviceRequest.statuses.completed": "Completed",
    "serviceRequest.statuses.cancelled": "Cancelled",
    "serviceRequest.create": "Create Request",
    "serviceRequest.addDetails": "Add Details",
    "serviceRequest.detailsPendingTitle": "Technician details pending",
    "serviceRequest.detailsPendingDesc": "Complete assessment, recommendation, and spare parts.",
    "serviceRequest.openRequest": "Open request",
    "serviceRequest.selectTechnician": "Select Technician",
    "serviceRequest.assignedTechnician": "Technician",
    "serviceRequest.assignedToMe": "Assigned to me",
    "serviceRequest.none": "None",

    // Spare parts in Service Request
    "serviceRequest.spareParts.title": "Spare Parts",
    "serviceRequest.spareParts.part": "Part name",
    "serviceRequest.spareParts.description": "Description (optional)",
    "serviceRequest.spareParts.quantity": "Qty",
    "serviceRequest.spareParts.cost": "Cost",
    "serviceRequest.spareParts.source": "Source/Supplier",
    "serviceRequest.spareParts.add": "Add",
    "serviceRequest.spareParts.remove": "Remove",
    "serviceRequest.spareParts.empty": "No spare parts needed.",
    "serviceRequest.spareParts.total": "Total: {amount}",
    "serviceRequest.spareParts.validation": "Please enter part name and quantity",
    "serviceRequest.ticketId": "Ticket ID",

    // Users
    "users.title": "Users",
    "users.role": "Role",
    "users.email": "Email",
    "users.displayName": "Display Name",
    "users.create": "Create",
    "users.passwordSetupNote": "After creating a user without a password, share the password setup link:",
    "users.copyLink": "Copy link",
    "users.copied": "Link copied",
    "users.copyError": "Failed to copy link",

    // Settings
    "settings.title": "Settings",
    "settings.subtitle": "Manage your account, preferences and appearance.",
    "settings.account": "Account",
    "settings.email": "Email",
    "settings.displayName": "Display name",
    "settings.phone": "Phone",
    "settings.phonePlaceholder": "e.g. +966 5XXXXXXXX",
    "settings.designation": "Designation",
    "settings.designationPlaceholder": "e.g. Biomedical Engineer",
    "settings.department": "Department",
    "settings.departmentPlaceholder": "e.g. Maintenance",
    "settings.resetPassword": "Reset password",
    "settings.saving": "Saving...",
    "settings.save": "Save changes",
    "settings.appearance": "Appearance",
    "settings.theme": "Theme",
    "settings.themeQuick": "Quick theme",
    "settings.themeHint": "Choose light, dark or system",
    "settings.language": "Language",
    "settings.selectLanguage": "Select language",
    
    // Sidebar
    "sidebar.menu": "Menu",
    "sidebar.home": "Home",
    "sidebar.inventory": "Inventory",
    "sidebar.serviceRequests": "Service Requests",
    "sidebar.manageUsers": "Manage Users",
    "sidebar.accountSettings": "Account / Settings",

    // Spare Parts
    "spareParts.title": "Spare Parts",
    "spareParts.addSparePart": "Add Spare Part",
    "spareParts.name": "Name",
    "spareParts.serialNumber": "Serial Number",
    "spareParts.quantity": "Quantity",
    "spareParts.manufacturer": "Manufacturer",
    "spareParts.supplier": "Supplier",
    "spareParts.noResults": "No spare parts found.",
    "spareParts.deleteTitle": "Delete Spare Part",
    "spareParts.deleteDescription": "Are you sure you want to delete \"{name}\"? This action cannot be undone.",
    "spareParts.addSuccess": "Spare part added successfully!",
    "spareParts.updateSuccess": "Spare part updated successfully!",
    "spareParts.deleteSuccess": "Spare part deleted successfully!",
    "spareParts.addError": "Failed to add spare part",
    "spareParts.updateError": "Failed to update spare part",
    "spareParts.deleteError": "Failed to delete spare part",
    "spareParts.nameRequired": "Name is required",
    "spareParts.adding": "Adding...",
    "spareParts.deleteConfirm": "Are you sure you want to delete this spare part?",
    "spareParts.namePlaceholder": "e.g., Air Filter",
    "spareParts.serialNumberPlaceholder": "e.g., SN-12345",
    "spareParts.quantityPlaceholder": "e.g., 10",
    "spareParts.manufacturerPlaceholder": "e.g., Acme Corp",
    "spareParts.supplierPlaceholder": "e.g., Parts Warehouse Inc.",
    
    // Attendance
    "attendance.title": "Attendance",
    "attendance.checkIn": "Check In",
    "attendance.checkOut": "Check Out",
    "attendance.viewRecords": "View Records",
    "attendance.logIn": "Log In",
    "attendance.logOut": "Log Out",
    "attendance.loggedInSuccess": "Logged in successfully",
    "attendance.loggedOutSuccess": "Logged out successfully",
    "attendance.logInError": "Failed to log in",
    "attendance.logOutError": "Failed to log out",
    "attendance.noPermission": "You do not have permission to view attendance records.",
    "attendance.print": "Print",
    "attendance.load": "Load",
    "attendance.report": "Attendance Report",
    "attendance.date": "Date",
    "attendance.noRecords": "No attendance records found for {date}",
    "attendance.name": "Name",
    "attendance.employeeId": "Employee ID",
    "attendance.logInTime": "Log In Time",
    "attendance.logOutTime": "Log Out Time",
    "attendance.signature": "Signature",
    "attendance.loadError": "Error loading attendance",
    
    // Common Actions
    "common.edit": "Edit",
    "common.delete": "Delete",
    "common.cancel": "Cancel",
    "common.save": "Save",
    "common.add": "Add",
    "common.create": "Create",
    "common.update": "Update",
    "common.confirm": "Confirm",
    "common.search": "Search",
    "common.filter": "Filter",
    "common.loading": "Loading...",
    "common.error": "Error",
    "common.success": "Success",
    "common.yes": "Yes",
    "common.no": "No",
    "common.searching": "Searching...",
    "common.results": "result|results",
    "common.noEquipmentFound": "No equipment found.",
    "common.searchPlaceholder": "Search equipment by name, tag number, or location",
    "common.open": "Open",
    "common.selectEquipment": "Select Equipment",
    "common.filterPlaceholder": "Type to filter by name or serial number...",

    // Dashboard Cards
    "dashboard.addEquipment": "Add Equipment/Device",
    "dashboard.addEquipmentDesc": "Register new devices into the system.",
    "dashboard.inventory": "Inventory",
    "dashboard.inventoryDesc": "View and manage all available equipment.",
    "dashboard.spareParts": "Spare Parts",
    "dashboard.sparePartsDesc": "Manage inventory of spare parts.",
    "dashboard.maintenanceSchedule": "Maintenance Schedule Preview",
    "dashboard.maintenanceScheduleDesc": "Check upcoming maintenance tasks.",
    "dashboard.maintenanceOverdue": "Maintenance Overdue",
    "dashboard.maintenanceOverdueDesc": "See devices with overdue maintenance.",
    "dashboard.jobOrder": "Job Order",
    "dashboard.jobOrderDesc": "Submit a new support or service request.",

    // Theme
    "theme.light": "Light",
    "theme.dark": "Dark",
    "theme.system": "System",
  },
  ar: {
    // Table
    "table.toggleDetails": "تبديل التفاصيل",
    // Common
    "common.noResults": "لا توجد نتائج",

    // Header
    "header.title": "جامعة حائل",
    "header.subtitle": "لوحة متابعة أجهزة طبية",
    "header.department": "قسم الصيانة",
    "header.facility": "إدارة المرافق",
    
    // Equipment Card
    "equipment.name": "الاسم",
    "equipment.upToDate": "محدث",
    "equipment.dueSoon": "مستحق قريباً",
    "equipment.overdue": "متأخر",
    "equipment.lastMaintenance": "آخر صيانة",
    "equipment.nextMaintenance": "الصيانة القادمة",
    "equipment.location": "الموقع",
    "equipment.inDays": "خلال {days} أيام",
    "equipment.overdueBy": "متأخر بـ {days} أيام",
    "equipment.every": "كل",
    "equipment.sparePartsRequired": "قطع غيار مطلوبة",
    "equipment.approved": "معتمد",
    "equipment.pendingApproval": "في انتظار الموافقة",
    "equipment.requestApproval": "طلب موافقة",
    "equipment.scheduleMaintenance": "جدولة الصيانة",
    "equipment.part": "الجزء",
    "equipment.edit": "تعديل",
    "equipment.inUse": "في الاستخدام",
    "equipment.notInUse": "غير في الاستخدام",
    "equipment.status": "الحالة",
    "equipment.markMaintenanceCompleted": "تم إنهاء الصيانة",
    "equipment.equipmentUpdated": "تم تحديث المعدة",
    "equipment.delete": "حذف",
    "equipment.deleteTitle": "حذف المعدة؟",
    "equipment.deleteDescription": "سيتم إزالة {name} من القائمة.",
    "equipment.noMaintenanceSchedule": "لا يوجد جدول صيانة",

    // Add Equipment Form
    "form.addNewEquipment": "إضافة معدة جديدة",
    "form.machineName": "اسم الماكينة",
    "form.partNumber": "رقم الجزء",
    "form.location": "الموقع",
    "form.maintenanceInterval": "فترة الصيانة",
    "form.lastMaintenanceDate": "تاريخ آخر صيانة",
    "form.sparePartsRequired": "قطع غيار مطلوبة للصيانة",
    "form.selectInterval": "اختر الفترة",
    "form.everyWeek": "كل أسبوع",
    "form.every2Weeks": "كل أسبوعين",
    "form.everyMonth": "كل شهر",
    "form.every3Months": "كل 3 أشهر",
    "form.every6Months": "كل 6 أشهر", 
    "form.everyYear": "كل سنة",
    "form.addEquipment": "إضافة معدة",
    "form.cancel": "إلغاء",
    "form.required": "*",
    "form.edit": "تعديل",
    "form.save": "حفظ",
    "form.back": "رجوع",
    "form.next": "التالي",
    "form.model": "الطراز",
    "form.manufacturer": "الشركة المصنعة",
    "form.serialNumber": "الرقم التسلسلي",
    "form.status": "الحالة",
    "form.selectStatus": "اختر الحالة",
    "form.subLocation": "موقع فرعي",
    "form.newInstallation": "تثبيت جديد",
    "form.working": "عملي",
    "form.repair": "إصلاح",
    "form.maintenance": "صيانة",
    "form.partReplacement": "إستبدال القطعة",
    "form.forInstallation": "للتثبيت",

    // Alerts
    "alert.allCurrent": "جميع المعدات محدثة",
    "alert.allCurrentDesc": "جميع جداول صيانة المعدات محدثة.",
    "alert.overdueMaintenance": "صيانة متأخرة",
    "alert.overdueCount": "{count} معدة متأخرة في الصيانة.|{count} معدات متأخرة في الصيانة.",
    "alert.dueSoon": "صيانة مستحقة قريباً",
    "alert.dueSoonCount": "{count} معدة مستحقة للصيانة خلال 7 أيام.|{count} معدات مستحقة للصيانة خلال 7 أيام.",
    "alert.scheduleOverview": "نظرة عامة على جدول الصيانة",
    
    // Search and Filter
    "search.placeholder": "البحث في المعدات...",
    "filter.byStatus": "تصفية حسب الحالة",
    "filter.allEquipment": "جميع المعدات",
    "filter.upToDate": "محدث",
    "filter.dueSoon": "مستحق قريباً",
    "filter.overdue": "متأخر",
    "filter.all": "الجميع",
    "search.noResults": "لم يتم العثور على معدات تطابق معاييرك.",
    // CSV
    "csv.export": "تصدير CSV",
    "csv.import": "استيراد CSV",
    "csv.importing": "جارٍ الاستيراد...",
    "csv.imported": "تم استيراد CSV بنجاح",
    "csv.noRows": "لا توجد بيانات في ملف CSV",
    "csv.missingHeaders": "حقول إلزامية مفقودة: {missing}",
    "csv.downloadTemplate": "تحميل القالب",
    "csv.templateDownloaded": "تم تحميل القالب بنجاح",
    // List label
    "list.label.showing": "عرض {from}-{to} من {total}",
    "list.label.filteredBy": "مفلترة حسب",
    "list.label.search": "بحث \"{q}\"",
    "list.label.status": "الحالة: {status}",
    "list.label.and": "و",
    
    // Toast Messages
    "toast.error": "خطأ",
    "toast.fillRequired": "يرجى ملء جميع الحقول المطلوبة",
    "toast.success": "نجح",
    "toast.equipmentAdded": "تم إضافة المعدة بنجاح",
    "toast.equipmentUpdated": "تم تحديث المعدة بنجاح",
    "toast.maintenanceScheduled": "تم جدولة الصيانة",
    "toast.maintenanceScheduledDesc": "تم جدولة الصيانة لـ {name}.",
    "toast.serviceRequestCreated": "تم إنشاء طلب الخدمة",
    "toast.serviceRequestUpdated": "تم تحديث طلب الخدمة",
    "toast.updated": "تم التحديث بنجاح",
    
    // Language
    "language.switch": "English",
    "language.current": "العربية",
    
    // Auth
    "auth.signOut": "تسجيل الخروج",
    "auth.brand.title": "جامعة حائل",
    "auth.brand.subtitle": "نظام صيانة المعدات",
    "auth.signup.title": "أنشئ حسابك",
    "auth.signup.name": "الاسم الكامل",
    "auth.signup.name.placeholder": "مثال: جين دو",
    "auth.signup.email": "البريد الإلكتروني",
    "auth.signup.email.placeholder": "you@example.com",
    "auth.signup.password": "كلمة المرور",
    "auth.signup.password.placeholder": "••••••••",
    "auth.signup.password.helper": "ثمانية أحرف على الأقل وتتضمن حرفاً ورقماً ورمزاً خاصاً.",
    "auth.signup.confirm": "تأكيد كلمة المرور",
    "auth.signup.confirm.placeholder": "••••••••",
    "auth.signup.submit": "إنشاء الحساب",
    "auth.signup.haveAccount": "لديك حساب بالفعل؟",
    "auth.signup.signIn": "تسجيل الدخول",
    "auth.error.nameEmailRequired": "يرجى إدخال الاسم والبريد الإلكتروني",
    "auth.error.passwordConfirmRequired": "يرجى إدخال كلمة المرور وتأكيدها",
    "auth.error.passwordsNoMatch": "كلمتا المرور غير متطابقتين",
    "auth.error.passwordWeak": "يجب أن تكون كلمة المرور 8+ أحرف وتتضمن حرفاً ورقماً ورمزاً خاصاً",
    "auth.success.accountCreated": "تم إنشاء الحساب. يرجى تسجيل الدخول.",
    "auth.pendingApprovalTitle": "الحساب بانتظار الموافقة",
    "auth.pendingApprovalDesc": "تم إنشاء حسابك وهو بانتظار الموافقة. يرجى التواصل مع المشرف أو المسؤول لتفعيل الوصول.",
    "priority.low": "منخفضة",
    "priority.medium": "متوسطة",
    "priority.high": "عالية",
    "priority.urgent": "عاجلة",

    // Service Request
    "serviceRequest.title": "طلب خدمة",
    "serviceRequest.manage": "إدارة",
    "serviceRequest.manageRequests": "إدارة طلبات الخدمة",
    "serviceRequest.newRequest": "إنشاء طلب خدمة",
    "serviceRequest.createTitle": "إنشاء طلب خدمة",
    "serviceRequest.editTitle": "تعديل طلب الخدمة",
    "serviceRequest.description": "املأ التفاصيل أدناه لإنشاء طلب خدمة.",
    "serviceRequest.basic": "الأساسي",
    "serviceRequest.details": "تفاصيل الفني",
    "serviceRequest.requestType": "نوع الطلب",
    "serviceRequest.selectType": "اختر النوع",
    "serviceRequest.types.preventive": "صيانة وقائية",
    "serviceRequest.types.corrective": "صيانة علاجية",
    "serviceRequest.types.install": "تركيب",
    "serviceRequest.types.assess": "تقييم",
    "serviceRequest.types.other": "أخرى",
    "serviceRequest.priority": "الأولوية",
    "serviceRequest.selectPriority": "اختر الأولوية",
    "serviceRequest.priorities.low": "منخفضة",
    "serviceRequest.priorities.medium": "متوسطة",
    "serviceRequest.priorities.high": "عالية",
    "serviceRequest.scheduledAt": "التاريخ/الوقت المجدول",
    "serviceRequest.problemDescription": "وصف المشكلة",
    "serviceRequest.problemPlaceholder": "صف المشكلة...",
    "serviceRequest.technicalAssessment": "التقييم الفني",
    "serviceRequest.assessmentPlaceholder": "أدخل التقييم الفني...",
    "serviceRequest.recommendation": "التوصية",
    "serviceRequest.recommendationPlaceholder": "أدخل التوصية...",
    "serviceRequest.viewEquipment": "عرض المعدة",
    "serviceRequest.status": "الحالة",
    "serviceRequest.approvalStatus": "حالة الموافقة",
    "serviceRequest.workStatus": "حالة العمل",
    "serviceRequest.statuses.pending": "بانتظار",
    "serviceRequest.statuses.approved": "معتمد",
    "serviceRequest.statuses.rejected": "مرفوض",
    "serviceRequest.statuses.completed": "مكتمل",
    "serviceRequest.statuses.cancelled": "ملغي",
    "serviceRequest.create": "إنشاء الطلب",
    "serviceRequest.addDetails": "إضافة التفاصيل",
    "serviceRequest.detailsPendingTitle": "تفاصيل الفني قيد الإكمال",
    "serviceRequest.detailsPendingDesc": "أكمل التقييم الفني، التوصية وقطع الغيار.",
    "serviceRequest.openRequest": "طلب مفتوح",
    "serviceRequest.selectTechnician": "اختر الفني",
    "serviceRequest.assignedTechnician": "الفني",
    "serviceRequest.assignedToMe": "معين لي",
    "serviceRequest.none": "لا يوجد",

    // Spare parts in Service Request
    "serviceRequest.spareParts.title": "قطع الغيار",
    "serviceRequest.spareParts.part": "اسم القطعة",
    "serviceRequest.spareParts.description": "الوصف (اختياري)",
    "serviceRequest.spareParts.quantity": "الكمية",
    "serviceRequest.spareParts.cost": "التكلفة",
    "serviceRequest.spareParts.source": "المصدر/المورّد",
    "serviceRequest.spareParts.add": "إضافة",
    "serviceRequest.spareParts.remove": "إزالة",
    "serviceRequest.spareParts.empty": "لم تتم إضافة قطع غيار.",
    "serviceRequest.spareParts.total": "الإجمالي: {amount}",
    "serviceRequest.spareParts.validation": "يرجى إدخال اسم القطعة والكمية",
    "serviceRequest.ticketId": "رقم التذكرة",

    // Users
    "users.title": "المستخدمين",
    "users.role": "الدور",
    "users.email": "البريد الإلكتروني",
    "users.displayName": "الاسم المعروض",
    "users.create": "إنشاء",
    "users.passwordSetupNote": "بعد إنشاء مستخدم بدون كلمة مرور، شارك رابط إعداد كلمة المرور:",
    "users.copyLink": "نسخ الرابط",
    "users.copied": "تم نسخ الرابط",
    "users.copyError": "تعذر نسخ الرابط",

    // Settings
    "settings.title": "الإعدادات",
    "settings.subtitle": "إدارة الحساب والتفضيلات والمظهر.",
    "settings.account": "الحساب",
    "settings.email": "البريد الإلكتروني",
    "settings.displayName": "الاسم المعروض",
    "settings.phone": "رقم الهاتف",
    "settings.phonePlaceholder": "مثال: +966 5XXXXXXXX",
    "settings.designation": "المسمى الوظيفي",
    "settings.designationPlaceholder": "مثال: مهندس أجهزة طبية",
    "settings.department": "القسم",
    "settings.departmentPlaceholder": "مثال: الصيانة",
    "settings.resetPassword": "إعادة تعيين كلمة المرور",
    "settings.saving": "جارٍ الحفظ...",
    "settings.save": "حفظ التغييرات",
    "settings.appearance": "المظهر",
    "settings.theme": "السمة",
    "settings.themeQuick": "سمة سريعة",
    "settings.themeHint": "اختر فاتحًا أو داكنًا أو النظام",
    "settings.language": "اللغة",
    "settings.selectLanguage": "اختر اللغة",
    
    // Sidebar
    "sidebar.menu": "القائمة",
    "sidebar.home": "الرئيسية",
    "sidebar.inventory": "المخزون",
    "sidebar.serviceRequests": "طلبات الخدمة",
    "sidebar.manageUsers": "إدارة المستخدمين",
    "sidebar.accountSettings": "الحساب / الإعدادات",

    // Spare Parts
    "spareParts.title": "قطع الغيار",
    "spareParts.addSparePart": "إضافة قطعة غيار",
    "spareParts.name": "الاسم",
    "spareParts.serialNumber": "الرقم التسلسلي",
    "spareParts.quantity": "الكمية",
    "spareParts.manufacturer": "الشركة المصنعة",
    "spareParts.supplier": "المورّد",
    "spareParts.noResults": "لم يتم العثور على قطع غيار.",
    "spareParts.deleteTitle": "حذف قطعة الغيار",
    "spareParts.deleteDescription": "هل أنت متأكد من حذف \"{name}\"؟ لا يمكن التراجع عن هذا الإجراء.",
    "spareParts.addSuccess": "تم إضافة قطعة الغيار بنجاح!",
    "spareParts.updateSuccess": "تم تحديث قطعة الغيار بنجاح!",
    "spareParts.deleteSuccess": "تم حذف قطعة الغيار بنجاح!",
    "spareParts.addError": "فشل في إضافة قطعة الغيار",
    "spareParts.updateError": "فشل في تحديث قطعة الغيار",
    "spareParts.deleteError": "فشل في حذف قطعة الغيار",
    "spareParts.nameRequired": "الاسم مطلوب",
    "spareParts.adding": "جارٍ الإضافة...",
    "spareParts.deleteConfirm": "هل أنت متأكد من حذف قطعة الغيار؟",
    "spareParts.namePlaceholder": "مثال: فلتر هواء",
    "spareParts.serialNumberPlaceholder": "مثال: SN-12345",
    "spareParts.quantityPlaceholder": "مثال: 10",
    "spareParts.manufacturerPlaceholder": "مثال: شركة أكمي",
    "spareParts.supplierPlaceholder": "مثال: مستودع القطع",
    
    // Attendance
    "attendance.title": "الحضور",
    "attendance.checkIn": "تسجيل الدخول",
    "attendance.checkOut": "تسجيل الخروج",
    "attendance.viewRecords": "عرض السجلات",
    "attendance.logIn": "تسجيل الدخول",
    "attendance.logOut": "تسجيل الخروج",
    "attendance.loggedInSuccess": "تم تسجيل الدخول بنجاح",
    "attendance.loggedOutSuccess": "تم تسجيل الخروج بنجاح",
    "attendance.logInError": "فشل تسجيل الدخول",
    "attendance.logOutError": "فشل تسجيل الخروج",
    "attendance.noPermission": "ليس لديك صلاحية عرض سجلات الحضور.",
    "attendance.print": "طباعة",
    "attendance.load": "تحميل",
    "attendance.report": "تقرير الحضور",
    "attendance.date": "التاريخ",
    "attendance.noRecords": "لم يتم العثور على سجلات حضور لتاريخ {date}",
    "attendance.name": "الاسم",
    "attendance.employeeId": "رقم الموظف",
    "attendance.logInTime": "وقت الدخول",
    "attendance.logOutTime": "وقت الخروج",
    "attendance.signature": "التوقيع",
    "attendance.loadError": "خطأ في تحميل الحضور",
    
    // Common Actions
    "common.edit": "تعديل",
    "common.delete": "حذف",
    "common.cancel": "إلغاء",
    "common.save": "حفظ",
    "common.add": "إضافة",
    "common.create": "إنشاء",
    "common.update": "تحديث",
    "common.confirm": "تأكيد",
    "common.search": "بحث",
    "common.filter": "تصفية",
    "common.loading": "جارٍ التحميل...",
    "common.error": "خطأ",
    "common.success": "نجح",
    "common.yes": "نعم",
    "common.no": "لا",
    "common.searching": "جارٍ البحث...",
    "common.results": "نتيجة|نتائج",
    "common.noEquipmentFound": "لم يتم العثور على معدات.",
    "common.searchPlaceholder": "بحث في المعدات حسب الاسم أو الرقم أو الموقع",
    "common.open": "فتح",
    "common.selectEquipment": "اختر المعدة",
    "common.filterPlaceholder": "اكتب للتصفية حسب الاسم أو الرقم التسلسلي...",

    // Dashboard Cards
    "dashboard.addEquipment": "إضافة معدة/جهاز",
    "dashboard.addEquipmentDesc": "تسجيل أجهزة جديدة في النظام.",
    "dashboard.inventory": "المخزون",
    "dashboard.inventoryDesc": "عرض وإدارة جميع المعدات المتوفرة.",
    "dashboard.spareParts": "قطع الغيار",
    "dashboard.sparePartsDesc": "إدارة مخزون قطع الغيار.",
    "dashboard.maintenanceSchedule": "معاينة جدول الصيانة",
    "dashboard.maintenanceScheduleDesc": "تحقق من مهام الصيانة القادمة.",
    "dashboard.maintenanceOverdue": "صيانة متأخرة",
    "dashboard.maintenanceOverdueDesc": "عرض الأجهزة ذات الصيانة المتأخرة.",
    "dashboard.jobOrder": "طلب عمل",
    "dashboard.jobOrderDesc": "تقديم طلب دعم أو خدمة جديد.",

    // Theme
    "theme.light": "فاتح",
    "theme.dark": "داكن",
    "theme.system": "النظام",
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>("en");
  
  const t = (key: string, params?: Record<string, unknown>) => {
    let text = translations[language][key as keyof typeof translations[typeof language]] || key;
    
    // Handle pluralization for count
    if (params?.count !== undefined && text.includes("|")) {
      const [singular, plural] = text.split("|");
      text = params.count === 1 ? singular : plural;
    }
    
    // Replace parameters
    if (params) {
      Object.keys(params).forEach(param => {
        text = text.replace(`{${param}}`, params[param] as string);
      });
    }
    
    return text;
  };
  
  const isRTL = language === "ar";
  
  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      <div className={isRTL ? "rtl" : "ltr"} dir={isRTL ? "rtl" : "ltr"}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};